/* paige showers
 * lighter codes
*/

public function paigeInTheShower():Boolean
{
	if (!paigeIsCrew()) return false;
	if (!pc.hasStatusEffect("Paige Showering")) return false;
	return true;
}

public function paigeDoItInTheShower():void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	processTime(5);

	output("Two’s company, after all. Maybe she’ll enjoy the extra set of hands to get at all those hard to reach spaces. You");
	if (!pc.isNude()) output(" strip naked and");
	output(" walk up to the closed door to Paige’s stall, knocking on it noisily. She stops her singing and yips in surprise. <i>“Paige, it’s me,”</i> you say. <i>“Got room for one more?”</i>");
	output("\n\n<i>“Oh, [pc.name],”</i> she says, sighing. <i>“Don’t startle me like that! The last thing I need is to slip and fall!”</i> You hear her footsteps approach the door, and the deadbolt slides away. The door swings open, and you’re greeted by Paige, soaked through to the skin in the warm, steamy water of her shower. <i>“Also, the answer is yes. Get in here, sexy.”</i>");
	output("\n\nYou step into her stall, letting the water fall onto you and soak into your [pc.skinFurScales]. The stall is spacious enough for two, and you have enough room to stand shoulder-to-shoulder, but that’s all. Still, that’s <i>more</i> than enough for the two of you, and how cozy you two like to get.");
	output("\n\n<i>“Mind getting my shoulders, sweet thing?”</i> she asks you, handing you the soap. You lather up and run the bar over her strong shoulder, rubbing it deep into the fine fur of her body. She moans in delight at your attention to her tense form, and she relaxes into your technique. <i>“That’s it, love, just like that.”</i>");
	output("\n\nYou wash her body with the soap, getting everywhere from her upper back to her tail, then wrapping around to her belly. Naturally, your hands are rather... explorative, and it’s only a matter of time before you’re getting into the crease of her breasts and down to her ass, getting her booty so clean you could eat off it.");
	output("\n\nPaige hums in delight and leans her body into your hands with your every sensual motion, thrusting out her tits when you wash them and bending at the waist just a little when you soap up her ass. <i>“If you keep this up, [pc.name], I think we both know where this is going to go,”</i> she says sultrily. It’s obviously an invitation, and you don’t pass it up; you wrap your other hand around her waist to play with her vagina");
	if (pc.hasCock()) output(" and hotdog [pc.eachCock] against her tight ass");
	output(" as you clean her thigh.");
	output("\n\n<i>“Well then,”</i> she says, straightening herself and wrapping one arm around your neck, holding her body close to yours. <i>“You did a good job in our yoga session today, so I think you could do with a reward. C’mon, [pc.name], let’s get dirty.”</i>");
	output("\n\nYou feel an odd wave of nostalgia wash over you – it’s as if you had experienced this same scenario before, in a different life. Your muscles act on a phantom memory, guiding yourself through alien motions that your mind recognizes but can’t place. All you consciously know is that you’re about to have sex with a toned, strong dog-woman in a cramped shower stall.");
	output("\n\nYour body knows what to do next. What is your weapon of choice?");

	//[=Penetrate Her=]
	if (!pc.hasCock()) addDisabledButton(0, "Penetrate Her", "Penetrate Her", "You need a dick for this.");
	else if (pc.cockThatFits(paige.vaginalCapacity(0)) < 0) addDisabledButton(0, "Penetrate Her", "Penetrate Her", "You’re too big.");
	else addButton(0, "Penetrate Her", penisRouter, [paigeTakesItLikeASqueakyCleanBitch, 65, false]);
	//[=Anal=]
	if (!pc.hasCock()) addDisabledButton(1, "Anal", "Anal", "You need a dick for this.");
	else if (flags["PAIGE_ANAL"] == undefined) addDisabledButton(1, "Anal", "Anal", "You’re not sure how well Paige would react if you tried to fuck her butt, and a place as slippery as a shower stall isn’t the best for that sort of experimenting. Maybe try pitching anal with her in her quarters first.");
	else if (pc.cockThatFits(paige.analCapacity()) < 0) addButton(1, "Anal", function():void
	{
		clearOutput();
		output("Bluntly, you ask Paige what her opinion is on anal. <i>“What, with you?”</i> she asks, leaning her ass back and trapping your [pc.cock] between her asscheeks expertly. You moan with pleasure, but before you get the wrong idea, she hums disapprovingly. She was actually using her ass to measure you! <i>“Sorry, sweet thing, but maybe not this time. We just finished a yoga session, and working a beast like that into my ass would be a workout in of itself. I’m up for anything else, though.”</i>");
		addDisabledButton(1, "Anal");
	});
	else addButton(1, "Anal", penisRouter, [paigeShowerButtsecks, 50, false]);
	//[=Tribadism=]
	if (pc.hasVagina()) addButton(2, "Tribadism", vaginaRouter, [paigeRubPussiesWithDogs, 0, 0, 0, false]);
	else addDisabledButton(2, "Tribadism", "You need want a vagina for this.");
	//[=Down On Her=]
	addButton(3, "Down On Her", paigeTastesLikeSoap);
	//[=Get Laid=]
	if (pc.hasCock()) addButton(4, "Get Laid", penisRouter, [paigeLayingInTheShowerLikeALazyDoggo, 50, false]);
	else if (pc.hasVagina()) addButton(4, "Get Laid", vaginaRouter, [paigeLayingInTheShowerLikeALazyDoggo, 0, 0, 0, false]);
	else addDisabledButton(4, "Get Laid", "Get Laid", "You need genitals for this.");
	//[=Double-Dicked=]
	if (!pc.hasCocks()) addDisabledButton(5, "Double-Dicked", "Double-Dicked", "You need two dicks for this.");
	else if (flags["PAIGE_ANAL"] == undefined) addDisabledButton(5, "Double-Dicked", "Double-Dicked", "You’re not sure how well Paige would react if you tried to fuck her butt, and a place as slippery as a shower stall isn’t the best for that sort of experimenting. Maybe try pitching anal with her in her quarters first.");
	else if (pc.cockThatFits2(paige.analCapacity()) < 0) addButton(5, "Double-Dicked", function():void
	{
		clearOutput();
		output("You hump against her, enjoying the warm, wet feel of her fur against your sensitive monsters. Paige moans out, enjoying the way you’re using her body, but freezes slightly when one of them begins to press and ply against her butthole. <i>“Sorry, sweet thing, but maybe not this time. Much as I’d love me some double-dickings, one of those things in my butt would be one too many. I’m down for something else, though.”</i>");
		addDisabledButton(5, "Double-Dicked");
	});
	else addButton(5, "Double-Dicked", paigeCoopCocks);
}

public function paigeTakesItLikeASqueakyCleanBitch(cock:int):void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	
	output("You rub your [pc.cock " + cock + "] in the cleft of her toned ass, the water from the shower lubing you both up. Paige coos, pressing her butt into you, enjoying the feel of you hot-dogging her, grinding and humping along with each of your teasing thrusts. You press and grip her tits, loving how the water in her fur makes them feel squishy and plush with each ministration. She loves the feel just as much, and turns her head to the side, silently asking for a kiss.");
	output("\n\nYou oblige, pressing your [pc.lips] to hers, running your tongue through her lips and over her own. It’s difficult to multitask between frotting her luscious asscheeks, playing with her pert C-cups, and lovingly making out with the hot Ausar girl, but you get by, with some help: Paige moves with you, humping and pressing and kissing, making sure you never miss a beat.");
	output("\n\n[pc.EachCock] rises, engorging with your lust, and it doesn’t take long at all until you’re ready to fuck Paige properly. You release one of her breasts, tickling your fingers down her stomach and her abdomen, over her pelvis and ultimately sliding one into her tunnel, feeling the eager heat and hearing the pleasured woofs of the woman before you. Your other hand releases her other breast, and she whines pleadingly, feeling your other fingers slide down her side and grip onto her ass, squeezing hard and pressing the one cheek against your still-humping [pc.cock " + cock + "].");
	output("\n\nHaving enough, you pull your mouth away from hers and lean your crotch back, repositioning your cock against her mons. She tenses, remaining perfectly still, her tail standing straight up her back in preparation for your penetration, which you teasingly hold back on for the moment. You instead start frotting her once more, dragging your hard, ready [pc.cock " + cock + "] against the fire of her pussy, and the sound of her whimpering just makes you harder. <i>“Please,”</i> she eventually whispers, her body shivering in anticipation. You comply, lining yourself up once more, and push forward, penetrating into her tight, welcoming pussy.");
	pc.cockChange();
	output("\n\nPaige leans forward and rests her arms on the stall, sighing in pleasure and backing her ass into your crotch. You thrust into her gently, getting yourself reacquainted with the unique feel of her tight pussy – she has such control over every one of her muscles, and she’s really using that to her advantage here. You grope along her shapely thighs, getting a good feel for her body once more, and tighten your fingers over whatever flesh yields to them. You start to rut her properly, fucking her at a casual pace, both of you still a little burnt from your yoga.");
	output("\n\n<i>“Oh yeah,”</i> she moans, wrapping her tail as much around your torso as she can, matching your steady pace and humping back up against you. <i>“Nice and slow, baby, mmm... just like that.”</i> You reply by leaning into her, pressing your [pc.chest] against her back and kissing at her neck while you keep up your fucking.");
	if (pc.hasCocks()) output(" Your [pc.cock " + (cock == 1 ? 0 : 1) + "] rubs up and down the crack of her ass lamely, though the way she clenches against you with every inward thrust makes every sensation worth the effort.");
	if (pc.isHerm()) output(" Your [pc.vagina] pulses longingly, jealous of the attention you’re giving to Paige’s own, and hungers for something to suffocate the fire built inside it.");
	output(" She moans appreciatively with you some more, loving the feel of your [pc.cock " + cock + "] in her.");
	output("\n\n<i>“Grab my boobs again,”</i> she requests; far be it from you to turn her down. Your hands rise, sliding through her wet fur, past her strong lats and up to her breasts, spreading your fingers and clamping down on them as she asked. She coos in response, and you begin to knead and play with her tits, every little action getting a different response. With your left hand, you flick her nipple between each of your fingers, while you pinch and pull the other with your right, massaging her chest sensually. She lets go of the stall wall and leans fully into you, pressing her back into your [pc.chest], and giving you more room to play with.");
	output("\n\n<i>“That’s it,”</i> she says lowly, loving the way you treat her body. She seems to get off as much on you touching and feeling her muscles that she’s worked so hard on as she does the actual sex. The more you feel her, the tighter she pulls you in, rocking her hips into you and taking her time letting you go. The water from the shower slowly grows colder, but you can tell from the heat not only at your crotch but also");
	if (pc.balls > 0) output(" across your [pc.sack] and");
	output(" down your thighs that she’s getting wet enough for the both of you all the while.");
	output("\n\nHer body jerks with everything you do to it: out, into your hands while you play with her tits, and onto your [pc.cock " + cock + "] with every thrust into her tight tunnel you make. Her whines and sighs quickly begin to rise and quicken, and with a few louder grunts, she cums onto you, clamping her cunt on you like a vice and doing her very best to coax everything out of you");
	if (pc.balls > 0) output("r [pc.balls]");
	output(". You’re not too far behind her, and with just a few more pumps, you’re shooting your load deep into her, pumping and fucking the whole time, making sure to get it in deep.");
	if (pc.hasCocks())
	{
		output(" Your [pc.cock " + (cock == 1 ? 0 : 1) + "] shoots its own load up and onto her lower back and the base of her tail, snug between the cheeks of her ass");
		if (pc.cocks.length >= 3) output(" while [pc.eachCock] sprays your jizz all over the place: the floor and the walls of the small stall in particular, but also on her ass, onto her tail, and down her legs. Most of it washes into the drain beneath you, but it’ll definitely take a bit of scrubbing for her to get really clean after this.");
		else output(".");
	}
	if (pc.isHerm()) output(" Your [pc.vagina] cums along with the rest of you, spurting your femcum down your legs, washing the inside of your thighs in your juices. The combined pleasure between your genitals makes your knees buckle – if only you had something, or someone, fucking you too!");
	output("\n\nYou two stay there, standing under the cold shower nozzle, basking in the glow of each other post-coitus. You begin to slide out when she clenches hard onto your [pc.cock " + cock + "]. <i>“Just a minute longer,”</i> she says, and you don’t fight her. You simply enjoy each other a while, your stiff [pc.cock " + cock + "] resting in her, and her just relaxing in your embrace. Eventually, you soften and slip out, and she relents. <i>“Good as ever, sweet thing,”</i> she says, and you return the compliment, giving her a loving, lingering kiss on her neck.");
	output("\n\nYou two spend the next few minutes keeping each other warm in the frozen cold shower water while you finish cleaning up. You get to drying each other off, flirting and groping some more, but it doesn’t progress any farther than that. She kisses you one last time after you slip on your effects, and you both leave the shower, looking forward to next time.");
	
	paigeShowerDone();
}

public function paigeShowerButtsecks(cock:int):void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	
	output("Remembering how much she enjoys a good anal dicking, you’re almost hesitant to ask, but the allure of her sweet, toned ass is too strong. You ask her if she’s up for some anal. She doesn’t answer – instead, she smiles greedily, leaning her ass back and trapping your [pc.cock " + cock + "] between her asscheeks expertly. You moan with pleasure while she glides her globes up and down, feeling your manhood rise and swell with each bob. Your hands are already on her butt, clenching the skin hard together while you thrust in the space between her. <i>“Well... alright. But only because I like you so much.”</i>");
	output("\n\nYou grip onto her hips, dragging your [pc.cock " + cock + "] through the crack of her ass, working yourself up further before you jump right in. Thanks to the shower, you’re both lubed up well enough, so it’s just you you’re both waiting on. Paige leans into the wall of the shower stall, bracing herself while trying to keep herself relaxed, although it’s difficult; the thought of taking you up her ass is making her a little short of breath. She’s tight as a vice, but you know she can take you. She’s just getting herself ready.");
	output("\n\nThe [pc.cockHead " + cock + "] of your [pc.cock " + cock + "] rubs against her rosebud in anticipation");
	if (pc.hasCocks()) output(" while your [pc.cock " + (cock == 1 ? 0 : 1) + "] entertains itself between her thighs, bumping and sliding pleasurably across her vulva");
	output(". She instinctively clenches her ass, and you give her a moment to relax before you stroke her there again. She loosens, and, almost teasingly now, you prod gently at her hole, implying but not acting just yet. She takes deep breaths, working to steady herself. <i>“Okay,”</i> she says, looking over her shoulder to you with a smile.");
	output("\n\nYou plan to take it easy on her. You realign yourself, pointing your [pc.cockHead " + cock + "] right at her hole, and slowly begin to push yourself in. On reflex, she inhales sharply, pressing her upper body into the wall some more. You reassure her and push in a little deeper, sliding a quarter of your [pc.cock " + cock + "] into her anus. She gasps, but doesn’t object. Another push, sliding in to halfway. A grunt, and she shuffles her feet slightly, getting more stability. Another push, nearly to the base. She gives out a whorish moan, and you wonder if she’s at her comfort limit. You push forward anyway, to your [pc.sheath], and gasp in pleasure and sigh with relief when she doesn’t object.");
	pc.cockChange();
	output("\n\nYou stay still for a moment, basking in the heat of her ass as she completely takes your [pc.cock " + cock + "]. The ring of her sphincter pulls and tightens around you, dragging the skin of your cock with each movement, and her inner muscles clench and message every fiber of your hard meat. You shuffle a bit, when Paige interrupts you. <i>“Just a sec,”</i> she says, rocking her hips some more, this way and that, trying to get a good feel for your dick in her ass. You let her take her time – it’s her ass you’re fucking. She eventually shuffles into a comfortable standing position, and with a nod, gives you the go ahead.");
	output("\n\nYou pull out to halfway, the water making the fuck tantalizingly tight without making it painful. When you push back in, Paige moans with the thrust, allowing herself to get pushed forward with your force. Out, back to halfway, and back in, feeling every one of her muscles ripple and shudder with your hump. Out, to three quarters, and back in: Paige gasps out, lowering her head, focusing on the feeling.");
	output("\n\nYou begin to fuck her right, thrusting into her at a nice and easy pace. Paige doesn’t make many noises, but eventually, her plain, unreadable grunts of exertion turn into feminine gasps of pleasure. You take that as your cue to speed up your thrusts a little, and before long, she’s bucking back against you, enjoying the ride herself.");
	output("\n\nEvery pleasured gasp from her is an invitation to fuck her harder, one you take gladly. Soon enough, you’re fucking her good, thrusting into her like a piston, loving the feel of her toned, strong booty in your hands and around your dick with the water refreshing your lube with every outward swing. Paige presses forward, her body into the stall wall, with her cheek pressed flat against it, her eye locking onto you. She ‘huhs’ with every shove you make into her, and she matches your every blow, fucking you right back.");
	output("\n\n<i>“Little harder,”</i> she asks, when you’re already going about as hard as you can. You sacrifice a bit of speed for power as you plunge harder into her, spearing her anus apart with your mighty [pc.cock " + cock + "], driving yourself harder into her. She relents more space, practically crawling herself up the wall, and you continue to go up to your " + (pc.balls > 0 ? "[pc.balls]" : "[pc.sheath]") + ", burying yourself into her voracious ass. With her body climbs her voice: a few pumps more and her moans become wails, loud enough that you’re sure someone else could hear you.");
	if (pc.libido() >= 45) output(" With any luck, that someone will come to investigate – you’re sure it wouldn’t take much convincing to start a party.");
	output("\n\n<i>“Harder!”</i> she demands, thrusting her ass back onto you. You’re not sure how much harder you can go.");
	if (pc.hasCocks()) output(" Any one of your dicks that’s not inside her is battering painfully around her ass as she continues to hit you with it, making it harder to focus on fucking her this way.");
	output(" <i>“<b>Harder!</b>”</i> she yells, almost viciously. You just keep going, hoping that she won’t notice you can’t fuck her ass any harder; your orgasm isn’t much farther off as it is, and you hope that Paige’s isn’t either. Her voices continues to rise even as she continues to make unreasonable demands, until finally, her words taper off into simple screams, and she orgasms, the wall, her inner thighs, and her lower stomach splattering with her cum. Her anus squeezes down on your member, making it all the more difficult to keep up brutalizing her ass.");
	output("\n\nThe muscles in her ass ripple and tighten, snapping around your cock, seemingly wanting to keep you there. It’s a fight to keep fucking her, but from how she keeps gasping with every thrust, she’s thankful you are. Your cum boils");
	if (pc.balls > 0) output(" in your [pc.balls]");
	output("; your cock stiffens");
	if (pc.isHerm()) output("; your lonely [pc.vagina] clenches at nothing");
	output("; and you cum into her, blasting robe after rope of your jism inside her.");
	if (pc.cocks.length > 2) output(" [pc.EachCock] blasts in time with your [pc.cock " + cock + "], each of your dicks pointing in a different direction. Your cum gets on everything: Paige, yourself, the stall – some even reaches as high as the shower nozzle.");
	else if (pc.hasCocks()) output(" Your [pc.cock " + (cock == 1 ? 0 : 1) + "] flails and erupts with your [pc.cock " + cock + "], spraying onto the wall in front of Paige and across the lips of her sex.");
	output("\n\nYou both pant from the rigorous sex, and when you’re both finished, you collapse onto Paige’s back, exhausted. You weren’t expecting her to take so much out of you. <i>“Wow,”</i> she finally manages to say, catching her own breath. <i>“Thanks for putting up with me being such a bossy bitch, [pc.name]. But it’s your fault, you know. You’re the one who awakened the anal-hungry monster within me.”</i> You’re aware of the beast you’ve created, you tell her, but truth be told, since your first session, it’s been a bit easier to keep up with her. She’s just that good of a yoga instructor.");
	output("\n\nWith some reluctance, she eventually lets go of your spent, flaccid [pc.cock " + cock + "], conceding. The water’s long-since turned cold, and you spend the remainder of your time together washing and drying each other off. She does all she can to entice you some more – she fondles your [pc.cock " + cock + "] and kisses your neck sensually, eager for some more anal-play, but you’re just too worn from her earlier energy. She pouts, but gives in, finally allowing you to slip on your effects and leave the shower in peace.");

	pc.energy(-15);
	
	paigeShowerDone(true);
}

public function paigeRubPussiesWithDogs(genId:int):void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	
	output("You fondle her full breasts, wet and heavy from the shower water beating down on them. She moans and leans into your touch as you squish and fondle her flesh, flicking and pinching at her nipples. You bend your head down and start kissing at her neck – trying to avoid getting any fur sticking to your tongue. She loves it, and drags her ass over your pelvis some more, humping against " + (pc.isHerm() ? "your [pc.cock], impishly wishing it were put to use. You have some other plans this time, though." : "your bare skin. The tone of her ass almost makes you wish you had a dick to fuck her with, but you’re sure she’ll give you a hell of a ride all the same."));
	output("\n\nOne hand leaves her breast, going down her stomach and tracing every one of her abs, and you sigh longingly, for effect – you know how she loves it when people notice her body. It has an effect on her, and you can feel her press harder into you, and tighten the hold she has around your neck while you continue to kiss her. Your hand travels lower, to her lower stomach, than to her waist, and, unceremoniously, you shove a finger into her pussy. She moans gently and bucks her hips just a little, rocking them on your finger, wanting you to go just a little deeper for her.");
	output("\n\nYou don’t, though. You thrust only up to your second knuckle, and you sporadically use your thumb to diddle her clit, making her jump and ‘ah!’ whenever she doesn’t expect it. You take your mouth of her neck and your other hand off her breast, to guide her face towards yours, and you kiss. Your tongues meet and play in each other’s open, ravenous mouths; you both curl and wrap around each other, feeling each other tense in squirm.");
	output("\n\nYour fingers continue to tease her: your index thrusts gently and shallowly into her pulling cunt, and you start to use the others to stroke and caress her vulva, pinching her lower lips between the lengths of your digits. She groans into your mouth at your treatment, and her tongue spazzes and tenses over and over again. She eventually breaks the kiss and looks you in the eye, her own eyes seductively narrowing and her mouth curled into a sexy grin. <i>“Just some foreplay today, [pc.name]?”</i> she asks, roiling her hips into your touch. <i>“You’re sure you’re not up for anything a bit more adventurous?”</i>");
	output("\n\nYou respond by removing your hand from her pussy. She almost looks hurt, longing for your fingers back. You surprise her by spinning her around by the shoulders and pressing her back up against the wall of the stall. Your left hand travels down her lats and her stomach, coming to a rest on her ass, while your right simply slaps down hard on her other cheek. You step into her, lifting her left leg up, and she gets your idea, wrapping it around your waist and pulling you in closer.");
	output("\n\nYou close the gap between your bodies, pressing your [pc.chest] into Paige’s own set of tits; pushing your stomach against her tight six-pack; and sliding your [pc.legs] between her thighs until your [pc.vagina] comes into delicious contact with hers. You both gasp slightly and you keep mostly still for a moment, only jostling a little to draw out the stimulation. Paige takes the initiative, and, with a long, sensuous drag, slides the lips of her tight pussy up and across yours, up and across your [pc.clit]");
	if (pc.isHerm()) output(" and all the way to the base of your now-straining, pre-leaking [pc.cock]");
	output(".");
	output("\n\nThe electrifying feel snaps you out of it. You hump her right back, drawing your genitals up and across hers, loving the way she bites her bottom lip from the feel. Her arms slide down to your own [pc.ass], gripping your cheeks for some leverage");
	if (pc.tone >= 50) output(", and she coos sexily, gripping and pulling at each of your toned, chiseled asscheeks, even giving one as hard a slap as her hand can manage");
	output(". You start to fuck against her in earnest, pressing and pumping, sliding and bucking against her, loving and living for the sounds and expressions she makes as you love her the way only another woman can.");
	output("\n\n<i>“Fuck yeah!”</i> she enthuses, spurring you harder into action. You lift her by her ass, speeding up your fucking, rutting against her vulva with your own [pc.vagina " + genId + "] as quick and as hard as you can. There’s nothing gentle about it: the way your two clits kiss against each other with each upswing sends waves and demands from your [pc.clit] to your head, and you eagerly obey them.");
	if (!pc.hasCock())
	{
		output(" Paige moves her hands up to your tits, her hands groping onto your [pc.chest], her palms pressing onto your [pc.nipples] mindlessly, and her tongue lolls and flags with each buck up against her you make.");
		if (pc.isLactating()) output(" Your milk streams from your [pc.chest] as Paige puts more of her weak pressure on them: it sprays from between her fingers and drips down the back of her hands on across her wrists.");
		for (var fuckNipples:int = 0; fuckNipples < pc.breastRows.length; ++fuckNipples)
		{
			if (pc.hasFuckableNipples(fuckNipples))
			{
				output(" Feeling the texture of your [pc.nipples " + fuckNipples + "] under her hands snaps her out of her reverie enough to think to stimulate you further by pressing into each with a thumb, fucking into and against you with each of your excited thrusts.");
				break;
			}
		}
	}
	else output(" Paige moves one hand to your [pc.chest] and wraps her other around your stiff [pc.cock], pumping it in time with your thrusts against her.");
	output("\n\nWith your whole body heaving into each of your thrusts, it’s not long before you’re brought to your peak. Your moan with an animalistic abandon, pressing forward, letting your [pc.vagina " + genId + "] kiss with hers one final time as your juices gush forth, coating and soaking into hers.");
	if (pc.isHerm()) output(" Your [pc.cock] explodes along with its sister, spurting your cum high between your pressed bodies, coating the underside of your breasts and your stomachs, but mostly onto Paige, who keeps your flow pointed towards her as she pumps you.");
	else output(" Paige continues to drive against you as she mauls your breasts, using her strong grip to grope what she can, eager to reach her own peak not far off.");
	output(" Paige’s moans rise and climb in her own ecstasy, until she climaxes along with you, returning the favor and spraying your crotch with her fluids, coating your [pc.vagina " + genId + "] with her own gift.");
	output("\n\nYou continue to thrust against each other for a bit, but eventually you wind down");
	if (pc.isHerm()) output(" and your [pc.cock] goes limp");
	output(" from all the excitement. Paige’s body shudders several times, feeling several miniature orgasms rip through her, until finally, she opens her eyes and meets yours. Without a sound, she pulls forward, making out with you once more, shamelessly gliding her tongue over yours. <i>“Leave it to a girl to know how to fuck another so well,”</i> she smiles, rubbing against you some more for emphasis.");
	if (pc.isHerm()) output(" <i>“Lucky for me, we won’t always have to choose.”</i> She gently strokes your waning erection some more, releasing you when the [pc.cockHead] touches down on her fur limply.");
	output("\n\nYou use what’s left of the shower water to clean yourselves of your lovemaking, and then you take turns playfully drying each other off. You start to feel the familiar heat rise in your loins from the way she works your towel on you, and from the way she acts, you don’t doubt she’s getting randy again herself. Sighing, you cut her off – you have other things to do today, unfortunately. She understands, and before you know it, you have your effects back on and you’re out the door.");

	pc.energy(-15);

	paigeShowerDone();
}

public function paigeTastesLikeSoap():void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	
	output("With your right hand, you fondle at her breast, kneading it gently and enticingly, squashing the nipple in the palm of your hand, while with your left, you scratch and rake your fingers across her abs, feeling every crest of every muscle. She giggles at your tickling and moans at your groping, leaning more of herself into you with each passing moment. Impishly, you ask her in a dull whisper if she’s got anything to eat.");
	output("\n\nPaige’s eyes open, and, after a confused moment, turns her head and says <i>“What?”</i> with a dumb expression. Hoping to be a bit clearer without making it obvious, you narrow your eyes and you lick your lips lavishly. It takes her another second before she catches your meaning. <i>“Oh!”</i> she nearly yelps, <i>“uh... yeah, I... yeah.”</i> Although you can’t tell, you’re sure she’s blushing, unable to come up with anything witty on the spot, and you laugh, kissing her lovingly on the cheek.");
	output("\n\nYou slide your left hand down to her pelvis, quickly coming to her vagina. You stroke her gently and rub the butt of your palm across her clit, playing with your food. Her breath catches and she jerks just slightly into your open hand, her body begging for more but you’re not quite ready to give it to her. Instead, you reach across her chest with your right hand, groping her other tit and using your forearm to press into her chest.");
	output("\n\nShe sighs and practically melts into your body, loving every touch and every twitch your fingers make to her delicate folds.");
	if (pc.hasCock()) output(" [pc.EachCock] begins to fill with your desire, desperate to replace your fingers, and it takes no small amount of willpower to deny yourself.");
	output(" You tease her entrance by barely slipping your finger in, just a centimeter or so; she responds by tensing when you enter and groaning when you leave. Your other hand lowers, dropping to her stomach and kneading at her muscles there instead, knowing how much she loves it when her ‘hard work’ gets appreciated.");
	output("\n\n<i>“Quit it,”</i> she moans, one of her own hands going down to her crotch. You expect her to push you in; to end your teasing with her satisfaction, but to your surprise, she actually pushes you away. <i>“I’m horny enough as it is. Fuck me with your face if you’re gonna already.”</i> You’re a bit surprised, but not really, at her forwardness, and you smile. With a rough twist, you spin Paige around, and shove her against the wall of the stall.");
	output("\n\nDespite what she just said, you don’t immediately drop down: you instead dive into her and kiss her passionately, sending her tongue and yours on a parade with each other, while you use your fingers to caress the muscles on her hamstrings and her glutes. She sighs into your mouth, feeling her exhale deeply the more you stroke her powerful muscles. You could probably make her cum just by making out with her, but you hunger for something tastier.");
	output("\n\nYou release her mouth and pull your tongue down her collarbone, tasting her (and her wet fur, unfortunately) with each motion you make. You bend at the [pc.legs] rather than your back as you’re brought level to her nipple, flicking and suckling on it for just a moment before you’re drawn farther down. Your pass by her belly and down to her bellybutton, pursing your lips on it for a moment. Down you continue, passing her waistline, and you make one more drawn out lick, going from just above her clit to the bottom of her stomach. She arches her back and thrusts out her hips in response, wanting you to get started already.");
	output("\n\nYou comply, and you drop down with a thud, pressing the flat of your tongue tightly against her button. She hisses and arches some more, and her knees buckle, while you don’t even move. You wait until she’s calmed down a bit before you lick upwards slowly, dragging your tastebuds across her clit, being careful not to overstimulate her too quickly. From the sound of her voice, your efforts pay off, and she just groans and shudders above you ferociously. <i>“Fuck,”</i> she breathes, and she places her hands on your scalp, weakly trying to pull you into her crotch.");
	output("\n\nYour lower yourself and plant your lips on her vulva, looking up to her eyes, finally beginning to deliver your promised lay. You give your tongue a bit of a break, kissing and suckling on her vulva, reaching as deep into her slit with just your face as you can go. She yips appreciatively: you move without much direction, opening your lips to cover as much of her quim as you can, giving her the most lewd kiss you can manage without your tongue. While you can’t tell how wet she is because of the water, the heat from her sex and the scent of her heady, thick musk is totally undeniable, " + (pc.hasCock() ? "and [pc.eachCock] pulls forward, pointing towards her like a compass to magnetic north, leaking your pre at her scent and ready to fuck her, or something, <i>anything.</i>" : "and you find yourself salivating – such a viable, powerful specimen like herself has you wishing you had a dick to fuck her with."));
	output("\n\nShe moans and rocks her body to her own rhythm, and you go with her, gripping onto her rock-hard calves and quadriceps. Your upper lip brushes up and across her clit while your lower simply stimulates her. Her hands grip onto your ears and drag across your head while she moans like a whore and grooves like an actress, and you’re part co-star and part prop.");
	output("\n\nYou’re tongue’s had enough of a break. It darts forward, splitting into her quickly, and you’re suddenly assaulted with her taste, coating every inch and nuance of your tongue. Her pussy clenches on your invading muscle, imprinting itself and its taste on your tongue, while Paige gasps above you and her fingers tighten on your scalp. It takes some effort to free yourself from her cunt, but you manage.");
	output("\n\nYou start down low, reaching as far between her legs as you can, the tip of your tongue just barely slipping across her taint. Her powerful thighs clench around you as you draw in and up, pushing in deep between her lips once more, and ending at her clit, giving it a long flick. Paige removes one of her hands, instead using it to play with her tit while she looks down at you lustfully. You’ve never turned your eyes away, though she sometimes tosses her head to the sides in her ecstasy while you continue to go down on her.");
	output("\n\nTwisting your tongue, you drill back into her, wiggling and swishing your tongue in her honeypot, loving how her face contorts and her body wriggles with your every motion. She humps and fucks into your face, and your hands clench hard onto her quads for stability, while her other hand tries to keep your face in place while she abuses it. Her hips roil and thrash; you tilt your face up some more, trying to get more space for your tongue to work, and your nose brushes hard against her clit with every forward thrust she makes. It drives her crazier.");
	output("\n\nHer tongue flops out of her mouth while she gasps with lust, lost in her little sex-consumed world while your work her like an expert. Her juices leak down your face unabated, over your upper lip and down your chin. Every time your nose crashes against her button, she ‘ah!’s, pauses a moment, and continues, drawing herself ever closer.");
	output("\n\nIt’s not too much longer before she drops her tit-feeling hand back down to your skull and her voice begins its telltale crescendo as her thrusts get more forced and erratic against your face. What starts as a few yips, becomes gasps, becomes grunts, becomes yells and shouts before she hits forward one last time, gushing her fluids out of her hole and straight into your thirsty maw. She cums and cums, her pussy tightening hard enough on your tongue to keep you from pulling away while she relentlessly pumps her fluid down your throat. What doesn’t flow into your mouth drenches your neck and your upper [pc.chest]; some of it even flows high enough to your forehead before dripping back down.");
	output("\n\nHer hands clench and unclench over and over, and she chews on her bottom lip nearly hard enough to draw blood. Since you’re clearly not going anywhere, you continue to service her even through her torrent. She hisses through clenched teeth hard as another orgasm eventually overcomes her, restarting her flood, albeit a bit drier this time. The process between you two continues for minutes, with her cumming half a dozen times, each time depositing more of her femcum into your stomach and across your body.");
	output("\n\nShe finally has enough, and her body goes slack against the wall of the stall. Your fingers release their death grip on her legs while she releases hers on your tongue, allowing you to finally withdraw it. You probably won’t be able to taste anything else for the rest of the day. She looks starry-eyed and a thousand miles away, and barely even notices when you climb back up. <i>“Fuck,”</i> is all she says, before she weakly reaches forward and hooks an arm behind your neck, pulling you in for another fierce kiss.");
	output("\n\nShe gives you all the tongue you could ask for, while you just sort of flap yours in directions. She doesn’t seem to mind, though, and eventually pulls away from you with a smile. <i>“Still hungry?”</i> she asks with a smile. You feel across your stomach – she probably just fed you for the day. You just look at her, figuring her question was rhetorical, and she giggles.");
	output("\n\nThe shower’s water went cold some time ago. Paige, for the most part, just needed to clean her crotch, while you have most of your front to vigorously scrub. Like a sweetheart, though, she sticks around, innocently helping you wash herself off of you. With her help, you’re clean before you know it, and then you’re drying each other off. " + (pc.hasCock() ? "[pc.EachCock] has hardly gone unnoticed this whole while, still standing at attention and begging, absolutely pleading for some action." : "Your own [pc.vagina] stands out, puffy and needy against the cold air, and it’s certainly not gone unnoticed.") + " Paige offers to return the favor, more than once, but you decline each time, knowing that if she did, it’d be a cycle between you two that would last for hours. She understands, but promises you that she owes you one.");
	output("\n\nYour drying goes by without incident, and before the end of the hour, your effects are back on and you’re out of the shower room.");
	
	pc.changeLust(25+pc.libido()/5);

	paigeShowerDone(false, false);
}

public function paigeLayingInTheShowerLikeALazyDoggo(genId:int):void
{
	clearMenu();
	clearOutput();
	showPaige(true);

	output("You step closer into her, wrapping your left arm around her torso diagonally, so that your hand rests on her right hip, and your reach over her chest with your right hand, grasping her left boob. You pull her into you, and she coos at the affection, enjoying your loving embrace, but doesn’t say anything, allowing you to have your way with her for now.");
	output("\n\nYou roll your hips into her tight, toned ass,");
	if (pc.hasCock()) output(" spearing your [pc.cock " + genId + "] between her cheeks wickedly, feeling it rise effortlessly against her soft fur and the smooth, strong muscles of her glutes");
	else output(" and with some clever maneuvering, you manage to wiggle her tail between your legs, and you feel the soft fur and the smooth, powerful muscles of her tail brush against your [pc.vagina " + genId + "], stimulating you easily");
	output(". You kiss and nip at her neck, knowing just what she likes, and she moans, knowing that you like hearing her.");
	output("\n\nYour hands work their magic on her taut body, touching her in all the right places, and paying some of her more defined muscles more attention in particular. While she gasps and lurches whenever you pull at a nipple or play with her button, she groans gutturally whenever you comb your fingers over her stomach muscles, or when you grasp her biceps with your whole hand. Whenever you lift your lips away from her neck for a breath or for better positioning, she drags her tongue across your face, half in thanks for your unspoken compliments and half in total lust.");
	output("\n\nWhile you love making her feel special,");
	if (pc.hasCock()) output(" your [pc.cock " + genId + "] continues to thrust and spear between her luscious ass, demanding attention be paid to it. Paige notices, and rocks her hips against you, squeezing your meat teasingly with each downstroke her ass makes on your [pc.cock " + genId + "]");
	else output(" your [pc.vagina " + genId + "] stokes with each swish her wet, heavy tail makes against you, hungering for something in it, and getting humped against by something as phallic as her tail just makes you hornier. Paige can tell from the way you keep dragging your [pc.hips] across her tail, and teases you however she can, by stiffening her tail and whipping it against your [pc.leg]");
	output(". <i>“Excited?”</i> she asks, grinning back at you. You let your actions speak for themselves, and you hump against her butt some more, dragging out your pleasure.");
	output("\n\nYou’re on the verge of just asking her to go down on you, when she reads your mind and breaches the topic herself. <i>“You’re a sexy little " + (pc.hasCock() ? "horndog" : "whore") + " sometimes, [pc.name],”</i> she says, turning herself around in your arms. She reaches down between you, stroking along " + (pc.hasCock() ? "[pc.eachCock], hissing inwardly at what she finds, loving the way her fingers, hurt as they are, just manage to glide across your skin" : "your [pc.vagina " + genId + "], grinning at how your lower lips just manage to wrap around her fingers like they were made for each other. Her thumb drags across your [pc.clit] intentionally, several times, and she smiles wider at every feminine grunt you make") + ". <i>“Feeling a little pent up, sweet thing?”</i> she asks innocently, her fingers working harder on your genitals. <i>“It’s okay. Paige’s in a giving mood.”</i>");
	output("\n\nShe leans in and gives you a quick, but fierce, kiss on the lips, sliding her tongue along your teeth just once before pulling away and lowering herself, sliding her eager tongue across your own neck, down your [pc.chest], across a [pc.nipple], and over your stomach. She comes to a rest on her knees, bringing herself level with your [pc.hips]; she eyes " + (pc.hasCock() ? "[pc.eachCock], now fully erect and at attention, just for her": "your [pc.vagina " + genId + "], loving how you can hardly resist fucking your hips at nothing in anticipation") + ", and, licking her drooling lips, leans in.");

	// Continue here if the PC is male or herm
	if (pc.hasCock())
	{
		switch (pc.cocks.length)
		{
			case 1: output("\n\nPaige opens her mouth and breaths hotly on your [pc.cock], hesitating just a moment to feel you jump in her hands, before taking you in. She only wraps her lips around the crown, suckling gently on you, lapping at any precum that flows out. Her tongue, though, runs out of her mouth unabated, lathering the underside of your [pc.cock] with her saliva, preparing it for the journey it’s about to take."); break;
			case 2: output("\n\nPaige grips onto [pc.eachCock] gently, keeping them sturdy and pointing them right at her lips. She pumps them alternately, watching how the skin glides with her fingers, while she ponders how precisely to pleasure you. Throwing caution to the wind, she opens her mouth as wide as she can, and shoves both of [pc.eachCock] into her mouth at once, suckling and laving at your rods gently, preparing both themselves and herself for the journey they’re about to take."); break;
			case 3: output("\n\nPaige isn’t quite sure where to begin, staring at [pc.eachCock]. She grabs ahold of your [pc.cock " + (genId == 2 ? 0 : 2) + "] with one hand, before grasping at your [pc.cock " + (genId == 1 ? 0 : 1) + "] with another, and seeing your [pc.cock " + genId + "] hanging loose and alone, she bends down and leans in, using just her face to lift it and shuck it into her mouth – only by the [pc.cockHead " + genId + "], and very gently, but nonetheless eagerly, spurred on by your jungle of a crotch for her to explore and conquer."); break;
			default: output("\n\nStill, she can’t quite tear her eyes from the rest of your cold, wet, and alone penises, and she sighs, almost out of frustration, completely unsure how she’s going to accomplish this."); break;
		}
		if (pc.hasVagina()) output("\n\nDespite her task, she’s fully aware of your feminine side, and gently leads one of her hands down the shaft of your [pc.cock " + genId + "], reaching back and between your legs for your other half. You gasp and buck as she finds your [pc.clit] first, and then thrusts her fingers in, up to the first set of knuckles. She pumps them in time with the dick in her mouth, trying to build up a rhythm with you.");
		output("\n\nYou groan and rest your hands on her head while she expertly goes down on you: she pays special attention to every noise and movement you make, and when you make a particularly sharp inhale or twitch in a particular way, she knows exactly why and how to make you do it again. She’s some kind of magician, the way she works her body to almost perfect synchronicity with yours – all for the end result of cumming in her mouth");
		if (pc.cocks.length > 2) output(" and all over the rest of her");
		output(".");
		output("\n\nShe moans and pushes herself deeper, swallowing more of your [pc.cock " + genId + "] into her tight, slurping maw: her head bobs and her tongue tastes, sucking more of your meat into her, eager to please. You pump your hips with her sucking, your fingers twirling and playing with her hair affectionately,");
		if (pc.cocks.length > 2) output(" enjoying how she tries her damndest to make sure every little bit of you has enough attention and is pleased to the best of her ability, no matter how much effort she requires");
		else output(" enjoying the lips of your Ausar lover as they slide over [pc.eachCock] and how she seems to enjoy herself so thoroughly");
		output(".");
		if (pc.isHerm())
		{
			output("\n\nSuddenly, she pulls away, leaving [pc.eachCock] out in the cold air and the beating of the shower water. You look at her questioningly, when she leans forward,");
			if (pc.balls > 0) output(" burying her muzzle underneath your [pc.sack] to push your [pc.balls] out of her way,");
			output(" and gets her tongue to work on your [pc.vagina]. You gasp, unintentionally squatting just a bit to get more of her. Ever the multi-tasker, she keeps her left hand busy, stroking your [pc.cock " + genId + "], making sure no part of you is ever left alone for long.");
			output("\n\nShe pushes her nose up, rubbing the bridge of her long dog-nose against your [pc.clit], knowing how much that’d get to you. From her position, she can’t reach very deep into your tunnel with her tongue, but she certainly does what she can: she licks and digs at your vulva, tasting every drop of juice you drip, and allows you to fuck against the fine fur on her face as she services you. With the work she does in your [pc.vagina] and with the way her expert hand continues to masturbate your [pc.cock " + genId + "], your body is horribly confused in which way to thrust against, but the sensations lighting up your mind nonetheless make it worthwhile.");
			output("\n\nEventually, Paige pulls back, releasing your [pc.cock " + genId + "] from her hand and stepping out from between your legs. She rolls her head on her neck a bit – staying in such a way for so long must have been a strain – and gets right back to work, sucking your [pc.cock " + genId + "] back into her mouth, deeper and faster this time. ");
			//9999 new paragraph?
		}
		else output("\n\n");
		output("Paige moans out loud, pressing herself farther in, loving the feel of your dick in her mouth as much as you do. Your [pc.cock " + genId + "] pulses and bounces with each of your heartbeats, and she can feel the jump in her mouth and across her tongue. She does everything she can to enhance your pleasure, from pressing your [pc.cock " + genId + "] against the roof of your mouth, to using the base of her tongue on your [pc.cockHead " + genId + "] while she toys with your shaft with the tip, to leaning in and taking all of you in her mouth at once and staying there for a moment. You let her know that her efforts are paying off with a wordless grunt and jerking your hips: you’re close, and she can tell.");
		output("\n\nShe picks up her pace, bobbing up and down on you faster and harder. You’re not fucking her face so much as she’s fucking you with her mouth.");
		if (pc.cocks.length > 2) output(" Her hands are practically a blur, up and down on [pc.eachCock] – she’s pulled them each down and towards her, aiming them towards their proper target.");
		if (pc.isHerm()) output(" Her fingers are straight as can be, pistoning into you roughly while her thumb frigs against your [pc.clit], and the feel of her enthusiastic fingers inside your [pc.vagina], massaging and caressing your walls, has you seeing stars.");
		output(" You’re not entirely positive if she’s giving you pleasure because she wants to, or if you’re just some perverse toy for her to suck on. Whatever the case, you’re not complaining, that’s for sure. Your hands grip hard onto her head, harder than you intend to, but that seems only to spur her on. It’s not much longer until you cum from her expertise.");
		if (pc.cumQ() < 350) output("\n\nYou blow your load into her sucking mouth, and she licks and laps at every drop. Your [pc.cock " + genId + "] shakes and explodes with your jizz, coating her hot mouth, but it’s never quite enough for her: she doesn’t stop her sucking, milking you of every drop of cum you can make. You fill her mouth once, and she audibly swallows hard, and you fill it once more before you’re depleted. She only calms down with her sucking once she’s beyond doubt that you gave her everything.");
		else if (pc.cumQ() < 1000) output("\n\nYou cum into her hungry mouth, and you do not disappoint the cum-hungry Ausar beneath you. You coat her tongue with your seed, blowing out her cheeks with your sperm, and she swallows quickly before your next blast fills her mouth to the brim again. You’re a faucet, and she’s your sink, taking every drop, clamping her lips securely on your [pc.cock " + genId + "] to keep anything from spilling out. Her throat works hard to keep up, but she manages, and by the time you’re finally depleted, she’s satisfied – if a little stuffed.");
		else output("\n\nPaige worked so very hard for your seed, and you’re not about to disappoint the cute Ausar sucking you off. Your eruption knocks her off guard: your jizz shoots all over her mouth and straight down her throat. When she’s halfway done with one load, you deposit another, not giving her a hope to keep up with your output. She clamps down on your [pc.cock " + genId + "] hard, trying to not let anything escape, but it’s hardly effective: seconds later, cum is leaking out from her mouth and out of her nose, before she relents and lets go, letting your [pc.cock " + genId + "] spray her in the face instead. You cum and you cum, coating her face and her neck with your offering; she groans gutturally, half in love with the scenario and half disappointed she lost the competition between your dick and her throat.");
		if (pc.cocks.length > 2) output(" She strokes along [pc.eachCock] while you orgasm, and the rest of you sprays with the one in her throat. She does her best to keep [pc.eachCock] pointed somewhere at herself, letting you spray her with your sperm over and over, from different angles. You’re barely able to pay attention with the ecstasy flowing from your groin, but you could swear she was smiling the whole while, moaning along with your every blast.");
		if (pc.isHerm()) output("\n\nThe hand in your pussy is finally rewarded for its diligence, and gets a heaping blast of femcum all over Paige’s hand, flowing down her wrist and dripping off at her forearm. Your [pc.vagina] pulls hard at her, milking her fingers for all the sperm it wishes it could get. Paige doesn’t stop her thrusting, even while she tries to focus on [pc.eachCock], sympathetic to your feminine requirements. You thank her by coming for her some more, soaking her arm even more than it was.");
	}
	// Continue here if the PC is female
	else
	{
		output("\n\nShe doesn’t waste any time and gets to work right away on your [pc.vagina " + genId + "]. She leans in and pulls her face up a bit, drawing her long nose across your [pc.clit] while her tongue goes to work piercing into your tunnel. You gasp and buckle, one hand on her head and keeping her in place with the other reaching up and grabbing onto the wall of the stall for stability. Paige works quickly and deeply into you, and you can feel every twitch and turn of her muscle inside of you, and every bump and movement her nose makes against your stiff button.");
		output("\n\nJust as you pull her face into your crotch, she reaches up to grasp onto your [pc.ass] and pull you into her, as well as she can. She alternates from fucking you hard with her face – moving quickly and harshly, side to side, front and back, thrusting her long, fat tongue and thrashing it every which way – and taking it a bit slowly, pursing her lips and sensually digging herself as deep into you as she can reach, kissing and loving you, making you squirm with carnal delight.");
		output("\n\nShe withdraws her tongue, making you whimper just a little, before she puts it back to work licking up between the lips of your sex and tapering it off by stroking your [pc.clit] with the tip of her tongue. She presses and laps at it, ever so gently, and gradually puts more of her tongue onto it, pressing the flat of it onto your button. She rises on her knees, sliding her tongue down your sensitive [pc.clit] until it’s resting on the back of her long doggy-tongue. From there, she takes long and laborious licks, angling her tongue to work between the folds of your [pc.vagina " + genId + "]. It’s a creative trick and it makes you moan like a slut.");
		output("\n\nYou close your eyes and bask in the feel of the warm water washing you both while the toned Ausar girl works your horny cunt between your legs. Her tongue works wonders on you, touching and licking you in just the right ways, sending your mind off and letting your body do all the work. You don’t even notice when Paige removes one of her hands from your [pc.ass], and it’s not until her body starts rocking a bit harder against you that you look down, seeing her masturbate herself while she works to bring you to orgasm.");
		if (pc.hasNippleCunts()) output("\n\nSeeing her frig herself along with you reminds you of your own ‘alternative outlets’. You keep your hand on her head, gently and reassuringly keeping her in place, while you use the other to toy with your [pc.nipple]. The tag-team of sensations between your sensitive [pc.vagina " + genId + "] getting expertly worked and the unusual penetration your fingers provide your [pc.chest] nearly sends you heaving, but stopping isn’t even an option to you. Your pump your fingers, feeling your [pc.nipple] clench and pull at them, and your breath nearly escapes you.");
		output("\n\nPaige moans, the sound muffled by her own tongue, which vibrates against your sex. With every deep, long lick she makes, you buck against her face, trying to fuck it like it were a cock. Eventually, her tongue gets tired of the double-play, and she sits back down to angle her tongue more directly into your [pc.vagina " + genId + "]. The feel of having it back into you so suddenly, coupled with how it thrashes and pounds against every nerve you have while it thrusts and tastes, puts you very close, and you pull on her hair, perhaps a little roughly, to tell her. She replies by working harder.");
		output("\n\nShe opens her mouth wider and bends down before spearing forward, penetrating you deeply than she has yet. You nearly cry out, managing to bite back your jubilation just in time – you don’t want any curious onlooker investigating the sound of a womanly scream." + (pc.libido() < 50 ? " That would almost be embarrassing enough to turn you off." : " You want this sexy bitch all for yourself, and you’ll be damned if you’re sharing. At least not until you’re done.") + " Paige, though, giggles through her mouthful of quim and thrusts again, enjoying the strained efforts you’re making to not cry out. Her hand jills hard and fast against her own neglected pussy, and from her actions, she’s maybe as close as you are.");
		output("\n\nYour [pc.hips] rock in time with her mouth, and through just a little more stimulation, the welcoming waves of your orgasm crash through you and into Paige’s mouth. You moan heatedly and your muscles tense while your [pc.vagina " + genId + "] pulls and squeezes on Paige’s tongue, and your cum floods from you and into her open mouth. What she doesn’t catch sprays all over her face and down her neck, and you fuck against her muzzle a bit more with each contraction, riding out your orgasm as long as you can. From the feminine gasps you can make out from her between blasts of your girl-cum, it sounds like Paige’s getting off herself.");
	}

	output("\n\nYou calm down from the explosive orgasm, your eyes crossed from the oral sex Paige just gave you. You see shapes and colors, barely able to see, as you slump against the wall of the stall. Paige barely moves beneath you, soaking in your cum");
	if (pc.cocks.length > 2) output(", and letting the excess wash from her fur half-heartedly");
	output(". Moments pass in a completely undecipherable blur to you, and when you can finally make sense of your surroundings, Paige’s standing up and has her tongue in your mouth.");
	output("\n\nYou finally start to kiss her back, trying to convince her that you’ve got more life in you than a mannequin. She coos when she finally feels movement, and you groan, tasting yourself on her tongue");
	if (pc.hasCock()) output(", snowballing what she hasn’t swallowed quite yet");
	output(". She cradles you in her strong arms until she’s done, and you pull away from the wall, still a bit wobbly. <i>“Was it good for you too, sweet thing?”</i> she asks. You barely nod.");
	output("\n\nThe shower’s water is fairly cold against you. When Paige finally lets you go, she offers to finish up her wash alone. You decline, of course – you went to the showers to get clean in the first place, and you’re both dirtier than when you started! You help each other wash off, completely innocently, and make your way to the lockers.");
	output("\n\nYou can’t help but keep stealing glances at her naked, powerful form, and before you’re done drying, you offer her to return the favor. It’s the least you can do, after all. Paige looks you over, smiling and biting her lower lip as she imagines it, but, with a frown, declines. <i>“Thanks, sweet thing,”</i> she says, <i>“but we’d probably just keep fuckin’ and suckin’ all day if I let you.”</i> You ask her what the harm in that is, and she playfully whips you with her towel. <i>“You owe me one, though, and don’t you forget it.”</i>");
	output("\n\nClean as a whistle and with your effects back on you, you wave farewell to your Ausar lover and leave the showers.");

	paigeShowerDone();
}

public function paigeCoopCocks():void
{
	clearMenu();
	clearOutput();
	showPaige(true);
	
	var buttCock:int = pc.cockThatFits(paige.analCapacity());
	var vagCock:int = pc.cockThatFits2(paige.analCapacity());

	output("You don’t bother saying much and choose to just rub yourself against the wet, matted fur of her ass for a bit. [pc.EachCock] begins to rise and stiffen, thawed by the heat of her body and the friction between you two: your [pc.cock " + vagCock + "] drives itself sensually between her thighs and across her sex, while your [pc.cock " + buttCock + "] enjoys the warmth and coziness of her ass, rubbing across her taint and teasing her anal ring. You don’t make any attempts at either hole – that comes later.");
	output("\n\nPaige giggles to herself, letting you jerk yourself off with her lower body. The [pc.cock " + vagCock + "] between her legs caresses and tickles against her pussy while [pc.cock " + buttCock + "] crawls devilishly up her butt and between her cheeks. She squeezes down on both, forcing you to rub a bit harder, which was just the reaction she was aiming for.");
	if (pc.isNaga()) output("\n\n<i>“Dunno if you reptiles got it better or worse,”</i>");
	else output("\n\n<i>“Got yourself an exotic set, sweet thing,”</i>");
	output(" she mentions, almost casually, while you continue to masturbate yourself on her.");
	if (pc.isNaga()) output(" <i>“Twice the dick means twice the fun... but twice the work, too. I’m up to the challenge, though, if you are.”</i>");
	else output(" <i>“It’s not too often you meet anyone that’s not half-snake sporting more than one. Mind if I put ‘em to the test?”</i>");
	output(" She rocks her hips a little higher, brushing the ring of her anus across your [pc.cockHead " + buttCock + "] while driving your [pc.cock " + vagCock + "] further across her labia. <i>“Let’s just hope this doesn’t turn me any more into a buttfucking freak, huh?”</i>");
	output("\n\nShe teases you both, rubbing her wet holes against your [pc.cock " + vagCock + "] and your [pc.cock " + buttCock + "], intent on bringing you to full mast before taking any sort of plunge. Your hands travel down to her toned, trim hips, and you grasp onto them sharply, helping her rock against you. She ‘mmm’s at the feel of your rough hands on her muscles, and the way to continue to drive [pc.eachCock] against her.");
	if (pc.cocks.length > 2) output(" Your other dicks rise as well, though not as quickly as the first two, jealous that they were chosen instead.");
	output("\n\nYou move your hands up, sliding your palms over every well-defined muscle and sinew, before they come to rest on her pert breasts, each of them filling your squeezing hands just right. She sighs with delight while you press and massage against her wet chest, and leans back, resting her hips on [pc.eachCock] and her back onto your own [pc.chest]. She reaches back with her hands, stroking your face, and you kiss her cheek, prompting her to turn so you can kiss her properly.");
	output("\n\nYour tongues work together, arousing you both, preparing [pc.eachCock] for the plunge and preparing herself, sexually and mentally, for the strain she’s volunteering to take for your pleasure. You were both well along before you had started, though: you’re not going to get much harder and she’s not going to get much wetter (all things considered). She disengages from you so she can turn herself around, straddling you once more, face-to-face. Her hips rise along with your [pc.cock " + vagCock + "] and your [pc.cock " + buttCock + "], until one head is pushing against her impatient cunt while the other rests against her butthole.");
	output("\n\nAs ready as you are, you don’t rush her. You hold her by the ass once again, keeping her steady against your body, while she leans into your [pc.chest], using one hand to stabilize herself and using the other to align your tools. When they’re both in position, she takes a deep breath, and starts to slide down.");
	output("\n\nThe [pc.cock " + vagCock + "] in her quim slides in tightly, but easily. The [pc.cock " + buttCock + "] pressing against her rim, though, takes a bit more convincing. She grits her teeth and closes her eyes in concentration, grinding her hips just slightly, back and forth, working the meat into her butt. Once the [pc.cockHead " + buttCock + "] pops in, she lets out a gasp, opening her eyes a bit, before focusing once again to work more of it into her. Her muscles relax and tense sporadically – no matter how much she loves getting fucked in the butt, it’s still not a usual thing for her, and for every inch her ass takes, another simultaneously slides into her pussy, stuffing her fuller than she’s ever felt.");
	pc.cockChange();
	output("\n\nYou can feel her glutes become rigid in your palms whenever she moves, the muscles practically turning to stone. The pressure on your [pc.cock " + buttCock + "] is both stimulating and a bit painful; you whisper encouraging nothings to her while your hands work on her cheeks, trying to get them to ease whenever she slides down a bit more. It takes some patience, but eventually, she gets you all into her, in both ends.");
	output("\n\nYou look down to her abdomen. Her abs are plainly visible, as she flexes again and again, making tiny adjustments to her resting on your crotch, and you delightedly feeling each one.");
	if (pc.cocks.length > 2) output(" The rest of you lamentably stands between you, leaking their pre uselessly between your bodies, pleading for some attention themselves.");
	if (pc.isHerm()) output(" Your [pc.vagina] clenches in time with its neighbor – you can easily imagine what it might feel like to have two dicks in you at once. You almost wish for it while you’re waiting for Paige’s go-ahead.");
	output(" Paige’s face contorts, not in pain but in concentration, while she fidgets with her ass and lower body, adjusting to both of her holes being so totally full. After moments of her positioning and repositioning herself, her eyes finally meet yours. <i>“Okay,”</i> she whispers, <i>“but... a bit gentler than what we’re used to, okay?”</i>");
	output("\n\nYou accede; it’s the least you can do in return. After all the effort she went through to right herself on you, you pull out from her, ruining all her hard work, and then thrust back in, slowly. Her breath catches in her throat, but she doesn’t object – you repeat yourself, pulling out just as far, and she shucks in some air once you thrust in. Her pussy squelches and squeezes, but not anything like her anal ring: it’s like she’s both trying to keep you in and trying to keep you from entering her body, all at once. Her muscles move and form around your [pc.cock " + vagCock + "] and your [pc.cock " + buttCock + "] with each movement you make, doing their best to shape themselves around both of your intruders.");
	output("\n\nYour fucking keeps steady and slow. Paige rocks her hips onto both of your cocks, alternating from taking one deeper than the other. As much as she just loves sex in general, it’s the alien feeling of being so full that keeps her from going any harder. She gasps and jerks with your every thrust, and you grunt, shoving yourself");
	if (pc.balls > 0) output(" down to your [pc.balls]");
	output(" deep into her. You can practically feel your two dicks rubbing against each other inside her with each thrust.");
	output("\n\nHer strained grunts slowly turn into pleasured moans with each thrust, and you take that as your cue to pick up the pace just a bit. It’s still by no means an easy task, with the way she’s putting so much pressure on you, but the ease of her muscles and the lubrication of the water make your thrusting somewhat smoother. She buries her face into your [pc.chest] while you continue to brutalize her pelvis, muffling her pleasured noises with your body.");
	output("\n\nHer hands go from the wall for her balance, down to your [pc.ass], grabbing a pair of handfuls for herself. For more leverage, she lifts her right leg and wraps it around your [pc.hips].");
	if (pc.cocks.length > 2) output(" Your extra equipment, painfully erect, squashes between your bodies, pointing right at the underside of her boobs and your own [pc.chest].");
	output(" You fuck her a bit more forcefully, but not any faster, for both your sakes. She moans into you: her body’s adjusted to the feel, and she’s more receptive of your actions.");
	output("\n\nPaige’s breathing slowly turns ragged, and her sighs and shudders become more forceful over time. She meets your every pump with her own, fucking along with you, her body learning to love the feel of having both of her holes filled. Her voice rises with each pound: just a few more later, and she orgasms, her body going taut and tense, making it all the harder to keep fucking her.");
	output("\n\nThe intense pressure makes it just a little harder-going, but the feel of having her entire body trap all of you, milking you for the cum it craves, spurs you into your own throes of orgasm. You grunt and lean forward, resting your head on her shoulder, as [pc.eachCock] sprays forth, blasting into her from every angle.");
	if (pc.cumQ() < 350) output(" Your jizz blasts into her, filling into her womb nice and comfortably and shooting deep into her bowels. Your both shake: her from the feeling of getting two doses of your cum at once and you from having your [pc.cock " + vagCock + "] and your [pc.cock " + buttCock + "] pleased so uniquely. Your orgasm goes for two, three, and four blasts, before tapering off to nothing inside of her.");
	else if (pc.cumQ() < 1000) output(" You cum hard, shooting your potent spunk into her thirsty cunt and her slurping asshole. Her orifices fill out quickly, stuffed full, but you don’t relent, shooting more and more into her. She groans out, feeling so much sperm pool inside her, and her breathing shortens while she tries to focus on the feeling. By the time you’ve finally finished inside her, your creamy jizz leaks from each of her holes.");
	else output(" Once your orgasm finally, powerfully overtakes you, a glimmer of a thought questions that maybe finishing inside her wasn’t the best idea. Your cum rockets into both her pockets and then some: the [pc.cock] in her vagina fills it to the brim in just a few spurts, and the [pc.cock " + buttCock + "] in her ass shoots and shoots into the rest of her, distending even her tight stomach and ruining her form. She grunts hard, gripping onto you while you fill her out, but the tightness from both your cocks makes keeping herself composed a harder task than she anticipated. Your orgasm goes for what seems like minutes, and when you’re finally done, she looks primed to pop like a balloon.");
	if (pc.cocks.length > 2) output(" Your [pc.eachCock] sprays from between you, launching its own jizz up and uselessly between you, forming a warm, sticky blanket between your stomachs. Some of it even crawls up between her cleavage, sticking them together from the inside, and with her pressed against you like this, it can’t wash off right away.");
	if (pc.isHerm()) output("\n\nYour [pc.vagina] pulses and cums, spraying its juices down your legs and splashing onto the floor. With every thrust you make into her while your fairer sex orgasms, you try to imagine something in it, to stimulate it and draw yourself out longer – with both your hands occupied and Paige focused on herself, your imagination is all you have. It works well enough, and with every clench, your [pc.vagina] rocks just a little more.");
	output("\n\nYou two stay like that for just a moment, basking in your afterglow with each other. Paige’s face is still lodged firmly in your [pc.chest], and, while you can still feel the errant twitch and squeeze from either part of her, her breathing calms and evens. Her arms and wobbly and her legs are shaky from the unreal session between you");
	if (pc.cumQ() >= 1000) output(" – she’s probably going to have trouble doing much of anything for a day or two until she ‘digests’ her load");
	output(". Wearily, she pulls herself away, just enough to look you in the eye, and, without a moment, leans in to kiss you, tongue and all.");
	output("\n\nYou both stay like that in the shower, long after [pc.eachCock] has deflated and fallen limp. It’s not until the shower turns frigid that you decide to finish cleaning yourselves and get a move on out of the showers. Despite how cold the water is, you keep each other warm; she gets to your hard-to-reach places and you reciprocate, getting at all the hard spots under her fur.");
	output("\n\nClean as a whistle, you two go to the lockers, pulling out your towels to dry yourselves. You’re both rather quiet and subdued through the whole thing – there isn’t really much to say, not that you need words. Paige tells you everything you need to hear by wrapping her towel around you both, under the pretense that she’s helping you dry, but from the lewd way she’s rubbing her body against you, and from the way her eyes narrow and curled, pursed lips come within inches of your own, or your [pc.nipples], she’s more than ready for a repeat performance. And from the stirring in [pc.eachCock], you’re almost ready to take her up on that. But, dredging up all the willpower you have, you manage to rebuff her – and her pleading dog eyes once you do. You have other things to do today.");
	output("\n\nThe rest of your drying continues without much incident, and before long, you have your effects back on you and you’re out of the showers, heading back towards the bridge.");

	paigeShowerDone(true);
}

public function paigeShowerDone(anal:Boolean = false, orgasm:Boolean = true):void
{
	processTime(25);
	if (orgasm) pc.orgasm();
	pc.shower();
	if (anal) IncrementFlag("PAIGE_ANAL");
	IncrementFlag("SEXED_PAIGE");
	IncrementFlag("SHOWERED_PAIGE");
	pc.removeStatusEffect("Paige Showering");
	addButton(0, "Next", mainGameMenu);
}