# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Dec 15 19:12:49 2010

import wx

import sys
import time


class RedirectText:
	def __init__(self,aWxTextCtrl):
		self.out=aWxTextCtrl

	def write(self,string):
		wx.CallAfter(self.out.AppendText, string)



import MapFrame as vizFrame


class MapEditorFrame(wx.Frame):

	VizEnable = True
	
	def __init__(self, *args, **kwds):
		kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.TAB_TRAVERSAL|wx.CLIP_CHILDREN
		wx.Frame.__init__(self, *args, **kwds)


		self.VizEnable = True

		self.__set_properties()
		self.__createLayoutObjs()
		self.__do_layout()
		

		
		self.filterTimer = wx.Timer(self)
		self.pollUpdate = wx.Timer(self)
		self.tbUpdate = wx.Timer(self)

		

		self.Bind(wx.EVT_CLOSE, self.quitApp)
		self.Bind(wx.EVT_TIMER, self.updateFilter, self.filterTimer)
		self.Bind(wx.EVT_TIMER, self.updateGUI, self.tbUpdate)



		

	def __set_properties(self):
		self.SetTitle("Map Editor")
		self.SetBackgroundColour(wx.SystemSettings_GetColour(wx.SYS_COLOUR_BTNFACE))

		self.SetSize((1000, 685))
		self.SetMinSize((400, 400))

		
	
	def __controlButtonsSizer(self):
		controlButtonsSizer = wx.BoxSizer(wx.HORIZONTAL)

		descText = "Map Editor"
		self.videoWinHeaderLabel = wx.StaticText(self, -1, descText)
		self.videoWinHeaderLabel.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "MS Shell Dlg 2"))
		controlButtonsSizer.Add(self.videoWinHeaderLabel, proportion=0, flag=wx.ALL, border=5)

		controlButtonsSizer.Add([1,1], proportion=1)

		self.somethingButton = wx.ToggleButton(self, -1, "DO THE THING")
		controlButtonsSizer.Add(self.somethingButton, proportion=0, flag=wx.EXPAND, border=5)



		return controlButtonsSizer
	
	def __statusWindowSizer(self):

		statusWinSizer = wx.BoxSizer(wx.VERTICAL)


		self.statusWin = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
		statusWinSizer.Add(self.statusWin, 1, wx.EXPAND, 0)

		print "Starting Up..."

		return statusWinSizer
	

	def __createLayoutObjs(self):

		self.DestroyChildren()			#Kill the Children!

	
		self.controlButtonsSizer = self.__controlButtonsSizer()


		

		#print "Starting Up..."
		

	def __do_layout(self):

		self.mainWindowSizer = wx.BoxSizer(wx.VERTICAL)
		
		
		self.mainWindowSizer.Add(self.controlButtonsSizer, proportion=0, flag=wx.EXPAND, border=0)
		
		self.vizPanel = vizFrame.ReadoutPanel(self, -1)
		self.mainWindowSizer.Add(self.vizPanel, proportion=2,  flag=wx.EXPAND)

		self.Layout()
		

		self.ClearBackground()
		self.SetSizer(self.mainWindowSizer)
		
		self.Layout()

		#print "Starting Up..."
		


	def quitApp(self, event): 
		print "Exiting"

		time.sleep(.1)

		#print queVars.cnf.datProcThread
		#print queVars.cnf.serThread

		self.vizPanel.Destroy()
		
		wx.Exit()

	def updateFilter(self, event):
		print "filterfired"
		pass



	def updateGUI(self, event):
		pass

# end of class MapEditorFrame


class MyApp(wx.App):
	
	def OnInit(self):
		wx.InitAllImageHandlers()
		MainFrame = MapEditorFrame(None, -1, "")
		self.SetTopWindow(MainFrame)

		#Set up the filter timer, and stop it.
		#It can then be restarted by simply calling filterTimer.Start()
		MainFrame.filterTimer.Start((1000/30), 0)	#30 hz update rate
		MainFrame.filterTimer.Stop()

		
		MainFrame.tbUpdate.Start(25, 0)
		MainFrame.Show()
		return 1

