public function initWargiiRooms():void
{
	rooms["WARGII B12"] = new RoomClass(this);
	rooms["WARGII B12"].roomName = "CONQUERED\nENTRANCE";
	rooms["WARGII B12"].description = "The entrance to Korg’ii Hold is ruined. The secret door, once majestic, has been reduced to shattered pieces. Cold blasts inward from the exposed tundra to the east. Warmer breezes waft in from the west, humid and comfortable. The door out lies just to the east, presently closed.\n\nSpears from numerous guards have been piled together against the walls. Though you spy spots of blood, there are no corpses or signs of death. Perhaps the cat-folk want the korgs alive?";
	rooms["WARGII B12"].planet = "PLANET: UVETO VII";
	rooms["WARGII B12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII B12"].moveMinutes = 2;
	rooms["WARGII B12"].westExit = "WARGII D12";
	rooms["WARGII B12"].addFlag(GLOBAL.INDOOR);
	rooms["WARGII B12"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII B12"].addFlag(GLOBAL.PUBLIC);
	//rooms["WARGII B12"].addFlag(GLOBAL.OBJECTIVE);
	rooms["WARGII B12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII D12"] = new RoomClass(this);
	rooms["WARGII D12"].roomName = "EAST\nTUNNEL";
	rooms["WARGII D12"].description = "Korg’ii Hold’s main thoroughfares look to have been carved from the rock by hand. You can only imagine how long it took, tunneling through the hard stone, all to find a stable shelter from Uveto’s biting cold. Their labors paid off, as warm drafts of humid air waft by continually. You could walk around naked inside here without feeling an ounce of chill. In fact, most of the korgonne did, before this place became a battleground.";
	rooms["WARGII D12"].planet = "PLANET: UVETO VII";
	rooms["WARGII D12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII D12"].moveMinutes = 2;
	rooms["WARGII D12"].eastExit = "WARGII B12";
	rooms["WARGII D12"].northExit = "WARGII D10";
	rooms["WARGII D12"].southExit = "WARGII D14";
	rooms["WARGII D12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII D12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII D12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII D12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII D10"] = new RoomClass(this);
	rooms["WARGII D10"].roomName = "EAST\nTUNNEL";
	rooms["WARGII D10"].description = "This polished stone tunnel burrows due north into the pillar. You can feel the care that went into carving it beneath every step, meeting your [pc.foot] with near-flawless craftsmanship. Scorch marks from laser weapons and explosive mar the walls. The simple dwelling to the east had its door closed tight - until it was blown free of its hinges. The inside is ransacked and worthless, missing valuables and an occupant alike.";
	//Traffic to the west is brisk. Korgs of all shapes and sizes push past you toward the obvious scent of cooking. A simple dwelling lies east, closed tight.";
	rooms["WARGII D10"].planet = "PLANET: UVETO VII";
	rooms["WARGII D10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII D10"].moveMinutes = 2;
	rooms["WARGII D10"].northExit = "WARGII D8";
	rooms["WARGII D10"].eastExit = "";
	rooms["WARGII D10"].southExit = "WARGII D12";
	rooms["WARGII D10"].westExit = "";
	rooms["WARGII D10"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII D10"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII D10"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII D10"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII D8"] = new RoomClass(this);
	rooms["WARGII D8"].roomName = "NORTHEAST\nCORNER";
	rooms["WARGII D8"].description = "Hot air filters through the rubble-filled stairwell to the north, carrying the faint smell of gunpowder, making your stomach turn. Either the korgonne collapsed it to cut slow the invaders down, or somebody got reckless with a high grade explosive. Whatever the cause, you’ll need to find another way to save Ula and the hold.";
	rooms["WARGII D8"].planet = "PLANET: UVETO VII";
	rooms["WARGII D8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII D8"].moveMinutes = 2;
	//rooms["WARGII D8"].northExit = "WARGII D6";
	rooms["WARGII D8"].eastExit = "";
	rooms["WARGII D8"].southExit = "WARGII D10";
	rooms["WARGII D8"].westExit = "WARGII F8";
	rooms["WARGII D8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII D8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII D8"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII D8"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII F8"] = new RoomClass(this);
	rooms["WARGII F8"].roomName = "NORTH\nTUNNEL";
	rooms["WARGII F8"].description = "The distinctive scent of charred, burning food broils out of the doorway to the south. A burning kitchen littered with shattered cookware tells you all you need to know about what happened here. Opposite the destroyed restaurant is a home with its door wide-open, a small stuffed doll on the ground. The tunnel runs on east and west.";
	rooms["WARGII F8"].planet = "PLANET: UVETO VII";
	rooms["WARGII F8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII F8"].moveMinutes = 2;
	rooms["WARGII F8"].northExit = "";
	rooms["WARGII F8"].eastExit = "WARGII D8";
	rooms["WARGII F8"].southExit = "";
	rooms["WARGII F8"].westExit = "WARGII H8";
	rooms["WARGII F8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII F8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII F8"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII F8"].addFlag(GLOBAL.NPC);
	rooms["WARGII F8"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII H8"] = new RoomClass(this);
	rooms["WARGII H8"].roomName = "NORTH\nTUNNEL";
	rooms["WARGII H8"].description = "Another doorway to the north marks the location of one of the many korgonne dwellings you’ve seen thus far. This one’s knob has been smashed off in a fit of violence. No other entrances present themselves, leaving only the paths to the east - the western half of the tunnel is plugged with a barricade of heavy stone and sharpened metal scrap. <b>If you want at the northwest stairwell, you’ll have to come at it from another angle.</b>";
	rooms["WARGII H8"].planet = "PLANET: UVETO VII";
	rooms["WARGII H8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII H8"].moveMinutes = 2;
	rooms["WARGII H8"].northExit = "";
	rooms["WARGII H8"].eastExit = "WARGII F8";
	rooms["WARGII H8"].southExit = "";
	rooms["WARGII H8"].westExit = "WARGII J8";
	rooms["WARGII H8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII H8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII H8"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII H8"].runOnEnter = wargiiH8Bonus;

	rooms["WARGII J8"] = new RoomClass(this);
	rooms["WARGII J8"].roomName = "NORTHWEST\nTUNNEL";
	rooms["WARGII J8"].description = "A sharp bend turns this tunnel to branch south and east as it loops around the first floor of Korg’ii Hold. Stairs lead away to the north, spiraling up and down into the farthest reaches of the hold. You can feel puffs of hot air steaming up from below, providing heat to the embattled clan and its invaders alike. Finally, a clear passage upward!";
	rooms["WARGII J8"].planet = "PLANET: UVETO VII";
	rooms["WARGII J8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J8"].moveMinutes = 2;
	rooms["WARGII J8"].northExit = "WARGII J6";
	rooms["WARGII J8"].eastExit = "WARGII H8";
	rooms["WARGII J8"].southExit = "WARGII J10";
	rooms["WARGII J8"].westExit = "";
	rooms["WARGII J8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J8"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J8"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII J10"] = new RoomClass(this);
	rooms["WARGII J10"].roomName = "WEST\nTUNNEL";
	rooms["WARGII J10"].description = "Dwellings lie to the east and west. One of them even has an intact door. The other has been ransacked, its innards spilled across the tunnel floor. Two spears are snapped in half between them. One of them is charred and flecked with red hot embers, and sizzling divot in the wall gives evidence to a battle at this locale.\n\nThe tunnel continues south, but the way north is obstructed by a barricade of heavy stone and sharpened metal scraps. <b>If you want to use the stairwell beyond, you’ll need to find another way!</b>";
	rooms["WARGII J10"].planet = "PLANET: UVETO VII";
	rooms["WARGII J10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J10"].moveMinutes = 2;
	rooms["WARGII J10"].northExit = "WARGII J8";
	rooms["WARGII J10"].eastExit = "";
	rooms["WARGII J10"].southExit = "WARGII J12";
	//rooms["WARGII J10"].westExit = "WARGII L10";
	rooms["WARGII J10"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J10"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J10"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J10"].runOnEnter = wargiiJ10Bonus;

	rooms["WARGII J12"] = new RoomClass(this);
	rooms["WARGII J12"].roomName = "WEST\nTUNNEL";
	rooms["WARGII J12"].description = "Scanning your locale, you spot a granite door to the east, covered with miniature craters from small-arms fire. It still successfully protects the single domicile beyond - and whatever korgs are cowering inside. The tunnel leads on to the north and south through the embattled pillar. Just looking at the walls, you can tell that Korg’ii Hold is in a time of terrible conflict. Scorch marks race across the walls in fractal spiderwebs of anger and discontent.";
	rooms["WARGII J12"].planet = "PLANET: UVETO VII";
	rooms["WARGII J12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J12"].moveMinutes = 2;
	rooms["WARGII J12"].northExit = "WARGII J10";
	rooms["WARGII J12"].eastExit = "";
	rooms["WARGII J12"].southExit = "WARGII J14";
	rooms["WARGII J12"].westExit = "";
	rooms["WARGII J12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII J14"] = new RoomClass(this);
	rooms["WARGII J14"].roomName = "SOUTHWEST\nCORNER";
	rooms["WARGII J14"].description = "Wrapping around the circumference of Korg’ii Hold, this passage forms a sort of primitive beltway for the subterranean settlement. Soot blankets the once-polished floor. You can still smell the acrid aroma of accelerant from an flamethrower. A gap in the wall to the south exposes a curling staircase that provides access to the floors above and below. Splotches of blood around the its entrance give testimony to the presence of a furious melee.";
	rooms["WARGII J14"].planet = "PLANET: UVETO VII";
	rooms["WARGII J14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J14"].moveMinutes = 2;
	rooms["WARGII J14"].northExit = "WARGII J12";
	rooms["WARGII J14"].eastExit = "WARGII H14";
	rooms["WARGII J14"].southExit = "WARGII J16";
	rooms["WARGII J14"].westExit = "";
	rooms["WARGII J14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J14"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII H14"] = new RoomClass(this);
	rooms["WARGII H14"].roomName = "SOUTH\nTUNNEL";
	rooms["WARGII H14"].description = "A pair of unconscious korgonne females rest against the north wall. Their paws are bound with woven metal cord, and matching pair of fluffy tranquilizer darts in their necks make sure they won’t be wiggling free any time soon. You don’t have time to mess with them, unfortunately. Your time is better served clearing the hold. An inscription of a mortar and pestle alongside the door to the north indicates the presence of some kind of shop, but the text is too riddled with bullets to decipher.";
	//Tails wagging, the citizens of Korg’ii Hold politely squeeze past you on their various errands. Jangly bracelets, necklaces, and piercings click and clack to the beat of their flouncing gaits, almost drowning out the hushed whispers that follow your path. An inscription alongside the northern door depicts a type of mortar and pestle.";
	rooms["WARGII H14"].planet = "PLANET: UVETO VII";
	rooms["WARGII H14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII H14"].moveMinutes = 2;
	rooms["WARGII H14"].northExit = "WARGII H12";
	rooms["WARGII H14"].eastExit = "WARGII F14";
	rooms["WARGII H14"].southExit = "";
	rooms["WARGII H14"].westExit = "WARGII J14";
	rooms["WARGII H14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII H14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII H14"].addFlag(GLOBAL.HAZARD);
	//Just has a signage message
	rooms["WARGII H14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII H12"] = new RoomClass(this);
	rooms["WARGII H12"].roomName = "HERBS &\nHAPPY";
	rooms["WARGII H12"].description = "";
	rooms["WARGII H12"].planet = "PLANET: UVETO VII";
	rooms["WARGII H12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII H12"].moveMinutes = 2;
	rooms["WARGII H12"].northExit = "";
	rooms["WARGII H12"].eastExit = "";
	rooms["WARGII H12"].southExit = "WARGII H14";
	rooms["WARGII H12"].westExit = "";
	rooms["WARGII H12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII H12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII H12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII H12"].addFlag(GLOBAL.COMMERCE);
	rooms["WARGII H12"].runOnEnter = nenneRoomTextBonerus;

	rooms["WARGII F14"] = new RoomClass(this);
	rooms["WARGII F14"].roomName = "SOUTH\nTUNNEL";
	rooms["WARGII F14"].description = "Scorching warmth carries you along through the tunnels of Korg’ii hold. This one stretches straight to the east and west, terminated by sharp turns to the north at each end. Flashes of fur and laser fire can be seen through the smoky corridor wherever you turn. Directly north of you is a double door, the seam split across a carving of a gilded coat.";
	rooms["WARGII F14"].planet = "PLANET: UVETO VII";
	rooms["WARGII F14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII F14"].moveMinutes = 2;
	rooms["WARGII F14"].northExit = "";
	rooms["WARGII F14"].eastExit = "WARGII D14";
	rooms["WARGII F14"].southExit = "WARGII F16";
	rooms["WARGII F14"].westExit = "WARGII H14";
	rooms["WARGII F14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII F14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII F14"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII F14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII F16"] = new RoomClass(this);
	rooms["WARGII F16"].roomName = "WARM\nCRUSTS";
	rooms["WARGII F16"].description = "“The Warm Crusts” was the local clothing store for all of your winter wear needs. Now it’s an empty wreck of a shop. Located within a relatively small cave, it was easy for the milodan invaders to ransack the most valuable items for themselves. Barely a scrap remains. The shopkeeper herself is nowhere to be seen.\n\n<b>You won’t be buying anything here unless you can liberate the hold!</b>";
	rooms["WARGII F16"].planet = "PLANET: UVETO VII";
	rooms["WARGII F16"].system = "SYSTEM: SIRETTA";
	rooms["WARGII F16"].moveMinutes = 2;
	rooms["WARGII F16"].northExit = "WARGII F14";
	rooms["WARGII F16"].eastExit = "";
	rooms["WARGII F16"].southExit = "";
	rooms["WARGII F16"].westExit = "";
	rooms["WARGII F16"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII F16"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII F16"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII F16"].addFlag(GLOBAL.COMMERCE);
	rooms["WARGII F16"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII D14"] = new RoomClass(this);
	rooms["WARGII D14"].roomName = "SOUTHEAST\nTUNNEL";
	rooms["WARGII D14"].description = "This sharp bend in the tunnel that encircles the ground floor of Korg’ii hold feels like standing in a winding chimney, complete with smoke. It isn’t quite choking - enough of the hold hasn’t caught fire for that, and you doubt the stone would burn well if it did. Still, it fogs the air with an oppressive sense of impending doom. One of the hold’s staircases lies south.";
	rooms["WARGII D14"].planet = "PLANET: UVETO VII";
	rooms["WARGII D14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII D14"].moveMinutes = 2;
	rooms["WARGII D14"].northExit = "WARGII D12";
	rooms["WARGII D14"].eastExit = "";
	rooms["WARGII D14"].southExit = "WARGII D16";
	rooms["WARGII D14"].westExit = "WARGII F14";
	rooms["WARGII D14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII D14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII D14"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII D14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII J6"] = new RoomClass(this);
	rooms["WARGII J6"].roomName = "NORTHWEST\nSTAIRS";
	rooms["WARGII J6"].description = "The polished stone of the walls is speckled with so many bits of raw savicite that the entire chamber is bathed in reflected green light. The stairs themselves are narrow in here, pressed in by particularly solid stone on either side. You can journey up into the top layers of Korg’ii Hold or down into the warm depths.\n\n<b>You cannot exit the stairwell here. There is a massive barricade of stone and sharpened metal plugging up the passage.</b>";
	rooms["WARGII J6"].planet = "PLANET: UVETO VII";
	rooms["WARGII J6"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J6"].moveMinutes = 2;
	rooms["WARGII J6"].northExit = "";
	rooms["WARGII J6"].eastExit = "";
	rooms["WARGII J6"].southExit = "WARGII J8";
	rooms["WARGII J6"].westExit = "";
	rooms["WARGII J6"].inExit = "WARGII P6";
	rooms["WARGII J6"].inText = "Up";
	rooms["WARGII J6"].outExit = "WARGII R20";
	rooms["WARGII J6"].outText = "Down";
	rooms["WARGII J6"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J6"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J6"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J6"].runOnEnter = wargiiJ6Bonus;

	rooms["WARGII J16"] = new RoomClass(this);
	rooms["WARGII J16"].roomName = "SOUTHWEST\nSTAIRWELL";
	rooms["WARGII J16"].description = "The upper half of this low-ceilinged stairwell is blockaded with so much stone furniture that you’d need an army of thraggen movers to get through in any reasonable amount of time. Even if you had a score of determined brutes, you wouldn’t want to risk taking fire from whoever is on the other side. It’ll be quicker to look for another way up.";
	//"The ceiling of this stairwell is almost claustrophobically low compared to the coreward facilities you’re used to, designed for tiny korgonne instead of varied galactic citizens. Someone carved railings into the walls, rather than bolting on something that might protrude out, the tool-toughened texture long ago worn into smooth comfort. Korgonne smile at you as they walk by. It would seem your presence is welcome.";
	rooms["WARGII J16"].planet = "PLANET: UVETO VII";
	rooms["WARGII J16"].system = "SYSTEM: SIRETTA";
	rooms["WARGII J16"].moveMinutes = 2;
	rooms["WARGII J16"].northExit = "WARGII J14";
	rooms["WARGII J16"].eastExit = "";
	rooms["WARGII J16"].southExit = "";
	rooms["WARGII J16"].westExit = "";
	//rooms["WARGII J16"].inExit = "WARGII P16";
	rooms["WARGII J16"].inText = "Up";
	rooms["WARGII J16"].outExit = "WARGII R30";
	rooms["WARGII J16"].outText = "Down";
	rooms["WARGII J16"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII J16"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII J16"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII J16"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII D16"] = new RoomClass(this);
	rooms["WARGII D16"].roomName = "SOUTHEAST\nSTAIRWELL";
	rooms["WARGII D16"].description = "These artfully carved stairs might have been made with incredible artistry and attention to detail, but the upward passage has been plugged up with a seemingly impassible wall of savicite-streaked boulders. There’s no gaps small enough to move through, and you don’t have time to try moving them. There has to be another way!";
	//"Just as you’ve seen elsewhere within Korg’ii Hold, these stairs were carved with great attention to detail. Artfully patterned metal inlays glitter beneath the light of ceiling-suspended crystals. Comfortable handgrips provide something for the young, drunk, or weak to hold on to. Landings spaced every dozen or so steps provide you a place to rest. An opening to the north vents back to the main floor of the hold.";
	rooms["WARGII D16"].planet = "PLANET: UVETO VII";
	rooms["WARGII D16"].system = "SYSTEM: SIRETTA";
	rooms["WARGII D16"].moveMinutes = 2;
	rooms["WARGII D16"].northExit = "WARGII D14";
	rooms["WARGII D16"].eastExit = "";
	rooms["WARGII D16"].southExit = "";
	rooms["WARGII D16"].westExit = "";
	//rooms["WARGII D16"].inExit = "WARGII V16";
	//rooms["WARGII D16"].inText = "Up";
	rooms["WARGII D16"].outExit = "WARGII X30";
	rooms["WARGII D16"].outText = "Down";
	rooms["WARGII D16"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII D16"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII D16"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII D16"].runOnEnter = wargiiEncounterStuff;

	/* 
		SECOND FLOOR! 
	*/

	rooms["WARGII V16"] = new RoomClass(this);
	rooms["WARGII V16"].roomName = "F2 SOUTHEAST\nSTAIRWELL";
	rooms["WARGII V16"].description = "Metallic inlays of fish swimming beneath silvered waves decorate the steps. The opulence seems to go all the way down, though it is difficult to be certain with the lower steps filled with boulders. You can smell the taint of sweat and fear sweaty bodies wafting up from gaps below. The way up is still closed off but not guarded. The important fighting is here and below...";
	rooms["WARGII V16"].planet = "PLANET: UVETO VII";
	rooms["WARGII V16"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V16"].moveMinutes = 2;
	rooms["WARGII V16"].northExit = "WARGII V14";
	rooms["WARGII V16"].eastExit = "";
	rooms["WARGII V16"].southExit = "";
	rooms["WARGII V16"].westExit = "";
	//rooms["WARGII V16"].outExit = "WARGII D16";
	rooms["WARGII V16"].outText = "Down";
	rooms["WARGII V16"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V16"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V16"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V16"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V14"] = new RoomClass(this);
	rooms["WARGII V14"].roomName = "EAST\nTUNNEL";
	rooms["WARGII V14"].description = "The corridors of Korg’ii Hold’s second level are narrower than the first, less suitable for large amounts of foot traffic and more easily defended. However no amount of defenses could prepare them for a massive surprise attack from a force that’s several whole technological generations ahead. The tunnel continues in similar fashion north.\n\nA staircase to the south offers passage back to the first floor.";
	rooms["WARGII V14"].planet = "PLANET: UVETO VII";
	rooms["WARGII V14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V14"].moveMinutes = 2;
	rooms["WARGII V14"].northExit = "WARGII V12";
	rooms["WARGII V14"].eastExit = "";
	rooms["WARGII V14"].southExit = "WARGII V16";
	rooms["WARGII V14"].westExit = "";
	rooms["WARGII V14"].outExit = "";
	rooms["WARGII V14"].outText = "Down";
	rooms["WARGII V14"].inExit = "";
	rooms["WARGII V14"].inText = "Up";
	rooms["WARGII V14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V14"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V12"] = new RoomClass(this);
	rooms["WARGII V12"].roomName = "T\nINTERSECTION";
	rooms["WARGII V12"].description = "The narrow tunnels split into a T-shape here. You can walk north or south to your choice of stairwells, or west in a passage that splits the middle of the Korg’ii Hold’s central mass.";
	rooms["WARGII V12"].planet = "PLANET: UVETO VII";
	rooms["WARGII V12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V12"].moveMinutes = 2;
	rooms["WARGII V12"].northExit = "WARGII V10";
	rooms["WARGII V12"].eastExit = "";
	rooms["WARGII V12"].southExit = "WARGII V14";
	rooms["WARGII V12"].westExit = "WARGII T12";
	rooms["WARGII V12"].outExit = "";
	rooms["WARGII V12"].outText = "Down";
	rooms["WARGII V12"].inExit = "";
	rooms["WARGII V12"].inText = "Up";
	rooms["WARGII V12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V10"] = new RoomClass(this);
	rooms["WARGII V10"].roomName = "EAST\nTUNNEL";
	rooms["WARGII V10"].description = "Recesses in the walls provide numerous ambush points along the passage, while the tunnel’s natural narrowness prevents more than one or two people from squeezing through at a time. The denizens of Korg’ii Hold exploited both of these to the best of their abilities. Small holes in the wall reveal the presence of hidden ambush chambers, though a charred hall in the wall has exposed the secret armory beyond, now ablaze. A T-intersection to the south offers passage to the west. A short distance to the north is a staircase.";
	rooms["WARGII V10"].planet = "PLANET: UVETO VII";
	rooms["WARGII V10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V10"].moveMinutes = 2;
	rooms["WARGII V10"].northExit = "WARGII V8";
	rooms["WARGII V10"].eastExit = "";
	rooms["WARGII V10"].southExit = "WARGII V12";
	rooms["WARGII V10"].westExit = "";
	rooms["WARGII V10"].outExit = "";
	rooms["WARGII V10"].outText = "Down";
	rooms["WARGII V10"].inExit = "";
	rooms["WARGII V10"].inText = "Up";
	rooms["WARGII V10"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V10"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V10"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V10"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V8"] = new RoomClass(this);
	rooms["WARGII V8"].roomName = "EAST\nTUNNEL";
	rooms["WARGII V8"].description = "Squeezing through this narrow passage, you come to a wall of shattered stone and rock. It blocks further passage north - toward what should be a stairwell. The korgonne likely collapsed it to ward off a milodan attack. The way south remains clear.";
	rooms["WARGII V8"].planet = "PLANET: UVETO VII";
	rooms["WARGII V8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V8"].moveMinutes = 2;
	//rooms["WARGII V8"].northExit = "WARGII V6";
	rooms["WARGII V8"].eastExit = "";
	rooms["WARGII V8"].southExit = "WARGII V10";
	rooms["WARGII V8"].westExit = "";
	rooms["WARGII V8"].outExit = "";
	rooms["WARGII V8"].outText = "Down";
	rooms["WARGII V8"].inExit = "";
	rooms["WARGII V8"].inText = "Up";
	rooms["WARGII V8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V8"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V8"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T12"] = new RoomClass(this);
	rooms["WARGII T12"].roomName = "NARROW\nTUNNEL";
	rooms["WARGII T12"].description = "This narrow east-west passage was once heavily ornamented. Now its artful decorations are missing or in ruins. Glowing crystals have vanished. Artfully carved bone is smashed into jagged shards. The lush carpeting suffers under stains from combat and sex alike. Some of the stuffed hunting trophies are perhaps the only things left intact. Not even the milodans dare to desecrate the bodies of prized Uvetan beasts - especially the enormous scaled lizard. The doorway to the is halfway open. Its latch was snapped in half.";
	rooms["WARGII T12"].planet = "PLANET: UVETO VII";
	rooms["WARGII T12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T12"].moveMinutes = 2;
	rooms["WARGII T12"].northExit = "";
	rooms["WARGII T12"].eastExit = "WARGII V12";
	rooms["WARGII T12"].southExit = "WARGII T14";
	rooms["WARGII T12"].westExit = "WARGII R12";
	rooms["WARGII T12"].outExit = "";
	rooms["WARGII T12"].outText = "Down";
	rooms["WARGII T12"].inExit = "";
	rooms["WARGII T12"].inText = "Up";
	rooms["WARGII T12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R12"] = new RoomClass(this);
	rooms["WARGII R12"].roomName = "NARROW\nTUNNEL";
	rooms["WARGII R12"].description = "Solid stone blocks the way north, hung on hinges so thick they make the korgonne seem thin by comparison. The blocky door is all is swarming with pictographs of every kind of korgonne: fishermen, craftsmen, warriors, hunters, and even some kind of primitive alchemist, to name a few. Long claw-marks streak through the most beautiful parts. On the opposite side is an empty weapon rack, its prizes taken by force. The narrow passage itself stretches away to the east and west.";
	rooms["WARGII R12"].planet = "PLANET: UVETO VII";
	rooms["WARGII R12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R12"].moveMinutes = 2;
	rooms["WARGII R12"].northExit = "WARGII R10";
	rooms["WARGII R12"].eastExit = "WARGII T12";
	rooms["WARGII R12"].southExit = "";
	rooms["WARGII R12"].westExit = "WARGII P12";
	rooms["WARGII R12"].outExit = "";
	rooms["WARGII R12"].outText = "Down";
	rooms["WARGII R12"].inExit = "";
	rooms["WARGII R12"].inText = "Up";
	rooms["WARGII R12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R12"].runOnEnter = wargiiEncounterStuff;

	/*
	rooms["WARGII V6"] = new RoomClass(this);
	rooms["WARGII V6"].roomName = "F2 NORTHEAST\nSTAIRWELL";
	rooms["WARGII V6"].description = "Curling, purple impurities in Korg’ii Hold’s stonework race along the stairs here, on the hold’s second level. Unfortunately, a burly body blocks further travel higher. You can step down the impeccably carved staircase or head out to the south into a well-defended passage. The vague scent of food wafts up from below.";
	rooms["WARGII V6"].planet = "PLANET: UVETO VII";
	rooms["WARGII V6"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V6"].moveMinutes = 2;
	rooms["WARGII V6"].northExit = "";
	rooms["WARGII V6"].eastExit = "";
	rooms["WARGII V6"].southExit = "WARGII V8";
	rooms["WARGII V6"].westExit = "";
	//rooms["WARGII V6"].outExit = "WARGII D6";
	rooms["WARGII V6"].outText = "Down";
	rooms["WARGII V6"].inExit = "";
	rooms["WARGII V6"].inText = "Up";
	rooms["WARGII V6"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V6"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V6"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII V6"].runOnEnter = korgiD12Bonus;*/

	rooms["WARGII P6"] = new RoomClass(this);
	rooms["WARGII P6"].roomName = "F2 NORTHWEST\nSTAIRWELL";
	rooms["WARGII P6"].description = "Savicite deposits in the walls bathe the staircase in sickly green light. Though the natives of Korg’ii Hold are unbothered by its presence, you doubt the milodans were so lucky, judging by the streaks of drying sexual fluids that clinging to the wall. You can climb back down or head south through the embattled hallway.";
	rooms["WARGII P6"].planet = "PLANET: UVETO VII";
	rooms["WARGII P6"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P6"].moveMinutes = 2;
	rooms["WARGII P6"].northExit = "";
	rooms["WARGII P6"].eastExit = "";
	rooms["WARGII P6"].southExit = "WARGII P8";
	rooms["WARGII P6"].westExit = "";
	rooms["WARGII P6"].outExit = "WARGII J6";
	rooms["WARGII P6"].outText = "Down";
	rooms["WARGII P6"].inExit = "";
	rooms["WARGII P6"].inText = "Up";
	rooms["WARGII P6"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P6"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P6"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P6"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII P8"] = new RoomClass(this);
	rooms["WARGII P8"].roomName = "DEFENSIVE\nPASSAGE";
	rooms["WARGII P8"].description = "Defensive recesses line to passage to either side, providing convenient places for Korg’ii warriors to spring ambushes from. The tunnel itself is quite narrow, especially for its larger invaders. A few paces north will place you in a stairwell.";
	rooms["WARGII P8"].planet = "PLANET: UVETO VII";
	rooms["WARGII P8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P8"].moveMinutes = 2;
	rooms["WARGII P8"].northExit = "WARGII P6";
	rooms["WARGII P8"].eastExit = "";
	rooms["WARGII P8"].southExit = "WARGII P10";
	rooms["WARGII P8"].westExit = "";
	rooms["WARGII P8"].outExit = "";
	rooms["WARGII P8"].outText = "Down";
	rooms["WARGII P8"].inExit = "";
	rooms["WARGII P8"].inText = "Up";
	rooms["WARGII P8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P8"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P8"].runOnEnter = wargiiEncounterStuff;
	
	rooms["WARGII P10"] = new RoomClass(this);
	rooms["WARGII P10"].roomName = "DEFENSIVE\nPASSAGE";
	rooms["WARGII P10"].description = "To the south, you can spy a T-intersection that branches off to the east. A spiral staircase caps off the tunnel to the north. Likewise, a second staircase offers passage to the upper and lower reaches of Korg’ii Hold alike.";
	rooms["WARGII P10"].planet = "PLANET: UVETO VII";
	rooms["WARGII P10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P10"].moveMinutes = 2;
	rooms["WARGII P10"].northExit = "WARGII P8";
	rooms["WARGII P10"].eastExit = "";
	rooms["WARGII P10"].southExit = "WARGII P12";
	rooms["WARGII P10"].westExit = "";
	rooms["WARGII P10"].outExit = "";
	rooms["WARGII P10"].outText = "Down";
	rooms["WARGII P10"].inExit = "";
	rooms["WARGII P10"].inText = "Up";
	rooms["WARGII P10"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P10"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P10"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P10"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII P12"] = new RoomClass(this);
	rooms["WARGII P12"].roomName = "T\nINTERSECTION";
	rooms["WARGII P12"].description = "A narrow tunnel splits off from the broader north-south passage to connect the east and west sides of Korg’ii Hold. You can see two doors that way, one silver and one stone. Further north and south there are naught but staircases, each offering passage to the ground floor.";
	rooms["WARGII P12"].planet = "PLANET: UVETO VII";
	rooms["WARGII P12"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P12"].moveMinutes = 2;
	rooms["WARGII P12"].northExit = "WARGII P10";
	rooms["WARGII P12"].eastExit = "WARGII R12";
	rooms["WARGII P12"].southExit = "WARGII P14";
	rooms["WARGII P12"].westExit = "";
	rooms["WARGII P12"].outExit = "";
	rooms["WARGII P12"].outText = "Down";
	rooms["WARGII P12"].inExit = "";
	rooms["WARGII P12"].inText = "Up";
	rooms["WARGII P12"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P12"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P12"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P12"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII P14"] = new RoomClass(this);
	rooms["WARGII P14"].roomName = "DEFENSIVE\nPASSAGE";
	rooms["WARGII P14"].description = "The architecture in this part of the hold is similar to that of old Terran castles. Scattered nooks line the walls to provide cover. Grooves in the floor provide better traction. Even soaked in the results of a bloody battle, you have no problem finding your footing. Darkened slits in some of the walls suggest the presence of hidden passages from which to lay an ambush.\n\nA staircase to the south offers passage to the other floors of Korg’ii Hold... or it would if it wasn’t blocked full of furniture. In the distance to the north, you spy another.";
	rooms["WARGII P14"].planet = "PLANET: UVETO VII";
	rooms["WARGII P14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P14"].moveMinutes = 2;
	rooms["WARGII P14"].northExit = "WARGII P12";
	rooms["WARGII P14"].eastExit = "";
	rooms["WARGII P14"].southExit = "WARGII P16";
	rooms["WARGII P14"].westExit = "";
	rooms["WARGII P14"].outExit = "";
	rooms["WARGII P14"].outText = "Down";
	rooms["WARGII P14"].inExit = "";
	rooms["WARGII P14"].inText = "Up";
	rooms["WARGII P14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P14"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P14"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P14"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII P16"] = new RoomClass(this);
	rooms["WARGII P16"].roomName = "F2 SOUTHWEST\nSTAIRWELL";
	rooms["WARGII P16"].description = "Somebody had the bright idea to blockade this stairwell, probably in an attempt hold back the milodan invasion. While it might have been a good idea at the time, its single accomplishment has been to slow your passage to the upper floors and little else. The milodan horde obviously found another way up, as evidenced by the broken weapons and battles to be found with every step. You’ll have to wade back into it, to the north.";
	rooms["WARGII P16"].planet = "PLANET: UVETO VII";
	rooms["WARGII P16"].system = "SYSTEM: SIRETTA";
	rooms["WARGII P16"].moveMinutes = 2;
	rooms["WARGII P16"].northExit = "WARGII P14";
	rooms["WARGII P16"].eastExit = "";
	rooms["WARGII P16"].southExit = "";
	rooms["WARGII P16"].westExit = "";
	//rooms["WARGII P16"].outExit = "WARGII J16";
	rooms["WARGII P16"].outText = "Down";
	rooms["WARGII P16"].inExit = "";
	rooms["WARGII P16"].inText = "Up";
	rooms["WARGII P16"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII P16"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII P16"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII P16"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R10"] = new RoomClass(this);
	rooms["WARGII R10"].roomName = "THRONE\nROOM";
	rooms["WARGII R10"].description = "Fragments of crystal lie scattered across the floor on a bed of gold chains. The mounting brackets are still attached, surrounded by piles of fragmented stone from when they were ripped from the ceiling. The intricate murals that run the length of the walls are obscured beneath a layer of half-rotten plant paste, leaving nothing but the few upright milodans unmolested. The hold’s enormous stone throne lies conspicuously empty. Its cushion rests against the wall, slumping under its own weight.\n\nFrom behind the curtains to the east comes the muffled sound of a struggle. Brutish grunts and Ula’s feminine cries nearly drown out her father’s stuttered protests.";
	rooms["WARGII R10"].planet = "PLANET: UVETO VII";
	rooms["WARGII R10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R10"].moveMinutes = 2;
	rooms["WARGII R10"].northExit = "WARGII R8";
	rooms["WARGII R10"].eastExit = "WARGII T10";
	rooms["WARGII R10"].southExit = "WARGII R12";
	rooms["WARGII R10"].westExit = "";
	rooms["WARGII R10"].outExit = "";
	rooms["WARGII R10"].outText = "Down";
	rooms["WARGII R10"].inExit = "";
	rooms["WARGII R10"].inText = "Up";
	rooms["WARGII R10"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R10"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R10"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII PLACEHOLDIE"].runOnEnter = korgiD12Bonus;

	rooms["WARGII R8"] = new RoomClass(this);
	rooms["WARGII R8"].roomName = "CHIEF’S\nARMORY";
	rooms["WARGII R8"].description = "Korg’ii Hold’s armory is in a sorry state. Shelves are smashed clean free of their moorings. Spears and crossbows lie smashed to pieces on the floor next to piles of savicite bolts. An ancient powder-banger is bent nearly in half, but the other more technologically advanced weapons are missing, presumably stolen already. You doubt you’ll find anything of use here, but it never hurts to check.";
	rooms["WARGII R8"].planet = "PLANET: UVETO VII";
	rooms["WARGII R8"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R8"].moveMinutes = 2;
	rooms["WARGII R8"].northExit = "";
	rooms["WARGII R8"].eastExit = "";
	rooms["WARGII R8"].southExit = "WARGII R10";
	rooms["WARGII R8"].westExit = "";
	rooms["WARGII R8"].outExit = "";
	rooms["WARGII R8"].outText = "Down";
	rooms["WARGII R8"].inExit = "";
	rooms["WARGII R8"].inText = "Up";
	rooms["WARGII R8"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R8"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R8"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII R8"].runOnEnter = korgiD12Bonus;

	rooms["WARGII T10"] = new RoomClass(this);
	rooms["WARGII T10"].roomName = "CHIEF’S\nBEDROOM";
	rooms["WARGII T10"].description = "";
	//The Chief’s bedroom is surprisingly bare. Yes, he has a large, comfortable-looking bed with more fluffy hides and cushions than you care to count, but the rest of the chamber is quite simple. A bone crate holds a pile of knick-knacks and primitive jewelry. A stolen mining crate, still-bearing the SteeleTech logo, sits against the east wall. Judging by the chair next to it, it serves dual use as a wardrobe and desk.
	rooms["WARGII T10"].planet = "PLANET: UVETO VII";
	rooms["WARGII T10"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T10"].moveMinutes = 2;
	rooms["WARGII T10"].northExit = "";
	rooms["WARGII T10"].eastExit = "";
	rooms["WARGII T10"].southExit = "";
	rooms["WARGII T10"].westExit = "WARGII R10";
	rooms["WARGII T10"].outExit = "";
	rooms["WARGII T10"].outText = "Down";
	rooms["WARGII T10"].inExit = "";
	rooms["WARGII T10"].inText = "Up";
	rooms["WARGII T10"].addFlag(GLOBAL.INDOOR);
	////rooms["WARGII T10"].addFlag(GLOBAL.PUBLIC);
	//rooms["WARGII T10"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T10"].addFlag(GLOBAL.BED);
	rooms["WARGII T10"].addFlag(GLOBAL.NPC);
	rooms["WARGII T10"].runOnEnter = encounterWarAlpha;

	rooms["WARGII T14"] = new RoomClass(this);
	rooms["WARGII T14"].roomName = "ULA’S\nCHAMBERS";
	rooms["WARGII T14"].description = "Ula definitely isn’t in her room. The sharp, orderly contours of her chambers offer few places to hide, and the Chieftain’s daughter herself does not maintain much clutter. Her storage chests look to have been rifled through by someone in a hurry. You’re left to take in the impressive view of the tundra through her window or admire the tidiness of her bed. The door to the north will return you to the hold’s embattled tunnels.";
	rooms["WARGII T14"].planet = "PLANET: UVETO VII";
	rooms["WARGII T14"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T14"].moveMinutes = 2;
	rooms["WARGII T14"].northExit = "WARGII T12";
	rooms["WARGII T14"].eastExit = "";
	rooms["WARGII T14"].southExit = "";
	rooms["WARGII T14"].westExit = "";
	rooms["WARGII T14"].outExit = "";
	rooms["WARGII T14"].outText = "Down";
	rooms["WARGII T14"].inExit = "";
	rooms["WARGII T14"].inText = "Up";
	rooms["WARGII T14"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T14"].addFlag(GLOBAL.NPC);
	////rooms["WARGII T14"].addFlag(GLOBAL.PUBLIC);
	//rooms["WARGII T14"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII T14"].runOnEnter = ulaRoomBonusFunc;

	/*===============================================
	|   BASEMENT LEVEL 1 - B1 						|
	===============================================*/

	rooms["WARGII R30"] = new RoomClass(this);
	rooms["WARGII R30"].roomName = "B1 SOUTHWEST\nSTAIRWELL";
	rooms["WARGII R30"].description = "A pack sits on the steps, abandoned. Its flap is open, and the contents are mostly gone, save for some rations that had a bite taken out of them before being thrown against the wall. You wipe your brow and look to the staircase. It’s warm and humid here, the heat wafting up from below. The tunnel north opens up prodigiously, though it bends away to prevent you from seeing too much. Still, signs of battle linger even here.";
	rooms["WARGII R30"].planet = "PLANET: UVETO VII";
	rooms["WARGII R30"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R30"].moveMinutes = 2;
	rooms["WARGII R30"].northExit = "WARGII R28";
	rooms["WARGII R30"].eastExit = "";
	rooms["WARGII R30"].southExit = "";
	rooms["WARGII R30"].westExit = "";
	rooms["WARGII R30"].outExit = "WARGII R43";
	rooms["WARGII R30"].outText = "Down";
	rooms["WARGII R30"].inExit = "WARGII J16";
	rooms["WARGII R30"].inText = "Up";
	rooms["WARGII R30"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R30"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R30"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R30"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R28"] = new RoomClass(this);
	rooms["WARGII R28"].roomName = "WARM\nTUNNEL";
	rooms["WARGII R28"].description = "It is positively balmy down here. No wonder the korgonne are so comfortable wandering around in the nude - and the milodans sweating so prodigiously. You stand at the west side of a long, east-west tunnel. A stairwell to the south provides access to the upper levels. There’s an archway a little ways to the east, leading into a large chamber.";
	rooms["WARGII R28"].planet = "PLANET: UVETO VII";
	rooms["WARGII R28"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R28"].moveMinutes = 2;
	rooms["WARGII R28"].northExit = "";
	rooms["WARGII R28"].eastExit = "WARGII T28";
	rooms["WARGII R28"].southExit = "WARGII R30";
	rooms["WARGII R28"].westExit = "";
	rooms["WARGII R28"].outExit = "";
	rooms["WARGII R28"].outText = "Down";
	rooms["WARGII R28"].inExit = "";
	rooms["WARGII R28"].inText = "Up";
	rooms["WARGII R28"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R28"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R28"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R28"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T28"] = new RoomClass(this);
	rooms["WARGII T28"].roomName = "WARM\nTUNNEL";
	rooms["WARGII T28"].description = "This wide-open tunnel is so much bigger than most of Korg’ii Hold’s passageways. You can see the reason why: through an archway to the north lies what must be the hold’s mostly pillaged storeroom. Plenty of boxes have been smashed open. Hide-wrapped bundles are gutted like fresh kills, spilling their prizes onto the floor. You’ll need to walk in for a closer look at any of it, but it looks like the best items have already been pilfered. The tunnel in which you stand stretches east and west toward two of Korg’ii Hold’s many stone-carved staircases.";
	rooms["WARGII T28"].planet = "PLANET: UVETO VII";
	rooms["WARGII T28"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T28"].moveMinutes = 2;
	rooms["WARGII T28"].northExit = "WARGII T26";
	rooms["WARGII T28"].eastExit = "WARGII V28";
	rooms["WARGII T28"].southExit = "";
	rooms["WARGII T28"].westExit = "WARGII R28";
	rooms["WARGII T28"].outExit = "";
	rooms["WARGII T28"].outText = "Down";
	rooms["WARGII T28"].inExit = "";
	rooms["WARGII T28"].inText = "Up";
	rooms["WARGII T28"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T28"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T28"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T28"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V28"] = new RoomClass(this);
	rooms["WARGII V28"].roomName = "WARM\nTUNNEL";
	rooms["WARGII V28"].description = "Down in the belly of Korg’ii Hold, the air is warmer, and the scent of battle and sweat is thick in the air. Dribbles of stale cum on the floor mark where some battlefield stress relief occurred. A broken rifle lies a few feet away, notched by the ‘v’-shaped cut of a heavy korgonne axe. This particular passage stretches east-west through the hold toward a pair of staircases. Midway to the west, there’s an archway on the north wall, leading to a stockroom of some kind.";
	rooms["WARGII V28"].planet = "PLANET: UVETO VII";
	rooms["WARGII V28"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V28"].moveMinutes = 2;
	rooms["WARGII V28"].northExit = "";
	rooms["WARGII V28"].eastExit = "WARGII X28";
	rooms["WARGII V28"].southExit = "";
	rooms["WARGII V28"].westExit = "WARGII T28";
	rooms["WARGII V28"].outExit = "";
	rooms["WARGII V28"].outText = "Down";
	rooms["WARGII V28"].inExit = "";
	rooms["WARGII V28"].inText = "Up";
	rooms["WARGII V28"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V28"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V28"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V28"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X28"] = new RoomClass(this);
	rooms["WARGII X28"].roomName = "WARM\nTUNNEL";
	rooms["WARGII X28"].description = "This balmy, wide tunnel stretches away to the west. In the distance you spot some kind of archway on the north wall, but little else save for the omnipresent smoky haze and distant, fighting figures. One of Korg’ii Hold’s many stairwells has an opening to the south, if you’d like to journey to a different level.";
	rooms["WARGII X28"].planet = "PLANET: UVETO VII";
	rooms["WARGII X28"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X28"].moveMinutes = 2;
	rooms["WARGII X28"].northExit = "";
	rooms["WARGII X28"].eastExit = "";
	rooms["WARGII X28"].southExit = "WARGII X30";
	rooms["WARGII X28"].westExit = "WARGII V28";
	rooms["WARGII X28"].outExit = "";
	rooms["WARGII X28"].outText = "Down";
	rooms["WARGII X28"].inExit = "";
	rooms["WARGII X28"].inText = "Up";
	rooms["WARGII X28"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X28"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X28"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X28"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X30"] = new RoomClass(this);
	rooms["WARGII X30"].roomName = "B1 SOUTHEAST\nSTAIRWELL";
	rooms["WARGII X30"].description = "Intricately worked metal inlays follow these stairs as they go deeper and higher into the hold. The artwork seems reflective of the destinations, with the pathway up flanked by depictions of various korgonne at rest in cuddly abodes. Meanwhile, the way down was once filled with patterns of embedded gemstones, but many have already been pried free from the steps. An opening to the north of this landing provides access to a rather large tunnel.";
	rooms["WARGII X30"].planet = "PLANET: UVETO VII";
	rooms["WARGII X30"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X30"].moveMinutes = 2;
	rooms["WARGII X30"].northExit = "WARGII X28";
	rooms["WARGII X30"].eastExit = "";
	rooms["WARGII X30"].southExit = "";
	rooms["WARGII X30"].westExit = "";
	rooms["WARGII X30"].outExit = "WARGII X43";
	rooms["WARGII X30"].outText = "Down";
	rooms["WARGII X30"].inExit = "WARGII D16";
	rooms["WARGII X30"].inText = "Up";
	rooms["WARGII X30"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X30"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X30"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X30"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T26"] = new RoomClass(this);
	rooms["WARGII T26"].roomName = "SOUTHWEST\nSTOREROOM";
	rooms["WARGII T26"].description = "To call Korg’ii Hold’s storeroom massive would be an understatement. The vaulted ceiling stretches up at least twenty or thirty feet - high enough for even the largest milodans to stand upright. You even see one darting around a corner, cradling a stolen box of who-knows-what under one arm. A room like this could supply the hold with a year’s worth of sustenance, assuming it wasn’t currently in the midst of being rapaciously plundered.\n\nA faint red glow emanates from the west, and gusts of hot air billow out from that direction, heating the room well enough to make Irestead seem positively chilly.";
	rooms["WARGII T26"].planet = "PLANET: UVETO VII";
	rooms["WARGII T26"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T26"].moveMinutes = 2;
	rooms["WARGII T26"].northExit = "WARGII T24";
	rooms["WARGII T26"].eastExit = "WARGII V26";
	rooms["WARGII T26"].southExit = "WARGII T28";
	rooms["WARGII T26"].westExit = "";
	rooms["WARGII T26"].outExit = "";
	rooms["WARGII T26"].outText = "Down";
	rooms["WARGII T26"].inExit = "";
	rooms["WARGII T26"].inText = "Up";
	rooms["WARGII T26"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T26"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T26"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T26"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T24"] = new RoomClass(this);
	rooms["WARGII T24"].roomName = "NORTHWEST\nSTOREROOM";
	rooms["WARGII T24"].description = "A burning rack of spears and other primitive weapons marks where the milodan invaders discovered one of Korg’ii Hold’s weapon stockpiles. The flames burn high, and the weapons themselves rendered into charred coals. Another rack sits nearby, untouched. This one is empty, and the unconscious guard lying facedown next to it suggests that this place once housed more valuable, technological devices. They’re all gone now.\n\nA comically small doorway stands on the west wall, hanging halfway open. Alien runes above it designate the place as something called “Earthshapers,” likely the village blacksmith.";
	rooms["WARGII T24"].planet = "PLANET: UVETO VII";
	rooms["WARGII T24"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T24"].moveMinutes = 2;
	rooms["WARGII T24"].northExit = "";
	rooms["WARGII T24"].eastExit = "WARGII V24";
	rooms["WARGII T24"].southExit = "WARGII T26";
	rooms["WARGII T24"].westExit = "WARGII R24";
	rooms["WARGII T24"].outExit = "";
	rooms["WARGII T24"].outText = "Down";
	rooms["WARGII T24"].inExit = "";
	rooms["WARGII T24"].inText = "Up";
	rooms["WARGII T24"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T24"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T24"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T24"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R24"] = new RoomClass(this);
	rooms["WARGII R24"].roomName = "\nEARTHSHAPERS";
	rooms["WARGII R24"].description = "The inside of the blacksmith’s shop is the definition of rustic. The walls are made of worn, uneven stone, with only small, bone sconces bearing dim torches to break it up. The floors are more polished, but are still notably worn and gritty, with only a few scattered pelts to keep walking on it from being painful. The store is separated into at least two chambers; the one you’re in, which is largely empty, sans a set of training dummies and a few sets of weapons and armor put on display, and what you can only assume is the forge, separated from the front room by a solid wall with a small door and a serving window.\n\nThe blacksmith herself is nowhere to be found.";
	rooms["WARGII R24"].planet = "PLANET: UVETO VII";
	rooms["WARGII R24"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R24"].moveMinutes = 2;
	rooms["WARGII R24"].northExit = "";
	rooms["WARGII R24"].eastExit = "WARGII T24";
	rooms["WARGII R24"].southExit = "";
	rooms["WARGII R24"].westExit = "";
	rooms["WARGII R24"].outExit = "";
	rooms["WARGII R24"].outText = "Down";
	rooms["WARGII R24"].inExit = "";
	rooms["WARGII R24"].inText = "Up";
	rooms["WARGII R24"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R24"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R24"].addFlag(GLOBAL.HAZARD);
	//rooms["WARGII R24"].addFlag(GLOBAL.COMMERCE);
	rooms["WARGII R24"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V24"] = new RoomClass(this);
	rooms["WARGII V24"].roomName = "NORTHEAST\nSTOREROOM";
	rooms["WARGII V24"].description = "Spending time inside this storeroom would be a nice break from the otherwise claustrophobic interior of the rest of the hold - if it wasn’t the site of a raging battle. For a moment, you wonder how the diminutive korgonne managed to hollow out this chamber, then you pull yourself back to the present to focus on forcing your way through the melee. The hold isn’t lost. Not yet.\n\nA wide archway to the north provides access to a roomy access tunnel. The storeroom itself continues on for quite a ways to the south and the west.";
	rooms["WARGII V24"].planet = "PLANET: UVETO VII";
	rooms["WARGII V24"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V24"].moveMinutes = 2;
	rooms["WARGII V24"].northExit = "WARGII V22";
	rooms["WARGII V24"].eastExit = "";
	rooms["WARGII V24"].southExit = "WARGII V26";
	rooms["WARGII V24"].westExit = "WARGII T24";
	rooms["WARGII V24"].outExit = "";
	rooms["WARGII V24"].outText = "Down";
	rooms["WARGII V24"].inExit = "";
	rooms["WARGII V24"].inText = "Up";
	rooms["WARGII V24"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V24"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V24"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V24"].runOnEnter = wargiiEncounterStuff;
	
	//rooms["WARGII PLACEHOLDIE"].runOnEnter = korgiD12Bonus;
	rooms["WARGII V26"] = new RoomClass(this);
	rooms["WARGII V26"].roomName = "SOUTHEAST\nSTOREROOM";
	rooms["WARGII V26"].description = "A whiff of salt and fish wafts by your nostrils as you stride through this part of the storeroom, and looking closely at the nearby bundles, you realize why. Dried, salted meat is stockpiled in abundance, flanked by small piles of herbs. The milodans haven’t bothered to pillage here yet - that or they figure they’ll have ample time to consume this seafood spread as part of a victory feast. The storeroom continues north and west.";
	rooms["WARGII V26"].planet = "PLANET: UVETO VII";
	rooms["WARGII V26"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V26"].moveMinutes = 2;
	rooms["WARGII V26"].northExit = "WARGII V24";
	rooms["WARGII V26"].eastExit = "";
	rooms["WARGII V26"].southExit = "";
	rooms["WARGII V26"].westExit = "WARGII T26";
	rooms["WARGII V26"].outExit = "";
	rooms["WARGII V26"].outText = "Down";
	rooms["WARGII V26"].inExit = "";
	rooms["WARGII V26"].inText = "Up";
	rooms["WARGII V26"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V26"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V26"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V26"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X20"] = new RoomClass(this);
	rooms["WARGII X20"].roomName = "B1 NORTHEAST\nSTAIRWELL";
	rooms["WARGII X20"].description = "A collapsed segment of tunnel above halves this otherwise flawless staircase’s usefulness. Zebra-striped with purplish striations in the walls and steps themselves, it burrows artfully deeper into the hold. You can exit south into a wide tunnel or climb down into the even warmer passages below.";
	rooms["WARGII X20"].planet = "PLANET: UVETO VII";
	rooms["WARGII X20"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X20"].moveMinutes = 2;
	rooms["WARGII X20"].northExit = "";
	rooms["WARGII X20"].eastExit = "";
	rooms["WARGII X20"].southExit = "WARGII X22";
	rooms["WARGII X20"].westExit = "";
	rooms["WARGII X20"].outExit = "WARGII X33";
	rooms["WARGII X20"].outText = "Down";
	//rooms["WARGII X20"].inExit = "WARGII D6";
	//rooms["WARGII X20"].inText = "Up";
	rooms["WARGII X20"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X20"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X20"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X20"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X22"] = new RoomClass(this);
	rooms["WARGII X22"].roomName = "LARGE\nTUNNEL";
	rooms["WARGII X22"].description = "This tunnel is taller and wider than those higher up in the hold, easily eight or nine feet high and just as wide across. It would seem the tribe took care to carve out a broad thoroughfare, which makes sense considering you can see a storeroom entrance a little ways to the west. Of course only made things easier for the milodan invaders. Even now, you can see their tall forms gleefully pillaging Korg’ii Hold’s stores. An archway in the wall to north provides access to a colorful staircase, if you’d like to journey elsewhere into the hold.";
	rooms["WARGII X22"].planet = "PLANET: UVETO VII";
	rooms["WARGII X22"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X22"].moveMinutes = 2;
	rooms["WARGII X22"].northExit = "WARGII X20";
	rooms["WARGII X22"].eastExit = "";
	rooms["WARGII X22"].southExit = "";
	rooms["WARGII X22"].westExit = "WARGII V22";
	rooms["WARGII X22"].outExit = "";
	rooms["WARGII X22"].outText = "Down";
	rooms["WARGII X22"].inExit = "";
	rooms["WARGII X22"].inText = "Up";
	rooms["WARGII X22"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X22"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X22"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X22"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V22"] = new RoomClass(this);
	rooms["WARGII V22"].roomName = "LARGE\nTUNNEL";
	rooms["WARGII V22"].description = "You can easily swerve around the fallen korgonne thanks to the tunnel’s spacious dimensions. Most are unconscious, but there are plenty masturbating as well, addled by potent aphrodisiac darts or rough milodan breedings. The enormous opening to the south reveals an even more enormous storeroom, its order spun into chaos as the milodan invaders set to pillaging. The tunnel itself leads away to the east and west, toward staircases at either end.";
	rooms["WARGII V22"].planet = "PLANET: UVETO VII";
	rooms["WARGII V22"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V22"].moveMinutes = 2;
	rooms["WARGII V22"].northExit = "";
	rooms["WARGII V22"].eastExit = "WARGII X22";
	rooms["WARGII V22"].southExit = "WARGII V24";
	rooms["WARGII V22"].westExit = "WARGII T22";
	rooms["WARGII V22"].outExit = "";
	rooms["WARGII V22"].outText = "Down";
	rooms["WARGII V22"].inExit = "";
	rooms["WARGII V22"].inText = "Up";
	rooms["WARGII V22"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V22"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V22"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V22"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T22"] = new RoomClass(this);
	rooms["WARGII T22"].roomName = "LARGE\nTUNNEL";
	rooms["WARGII T22"].description = "The walls here are pitted in places, the holes filled with glass to transform flaws into reflective art. Of course, some of the pits are more recent. Blackened pockmarks show where core weapons have defaced the korgonne’s simple beauty. You can spy where the short-statured miners made the decision to chisel valuable minerals out of the wall, and the subsequent attempts to improve the look with skillful craftsmanship. This large tunnel leads east and west toward stairwells at each end. An entrance to a storeroom lies a little ways east.";
	rooms["WARGII T22"].planet = "PLANET: UVETO VII";
	rooms["WARGII T22"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T22"].moveMinutes = 2;
	rooms["WARGII T22"].northExit = "";
	rooms["WARGII T22"].eastExit = "WARGII V22";
	rooms["WARGII T22"].southExit = "";
	rooms["WARGII T22"].westExit = "WARGII R22";
	rooms["WARGII T22"].outExit = "";
	rooms["WARGII T22"].outText = "Down";
	rooms["WARGII T22"].inExit = "";
	rooms["WARGII T22"].inText = "Up";
	rooms["WARGII T22"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T22"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T22"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T22"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R22"] = new RoomClass(this);
	rooms["WARGII R22"].roomName = "LARGE\nTUNNEL";
	rooms["WARGII R22"].description = "Warm air lazily blows through this large tunnel on its way to the stairwell to the north. Korg’ii Hold’s natural geothermal heat must make living here quite comfortable for the natives - and a living hell for the armored invaders. You’re glad for the extra room the size of this tunnel affords as you do your best to maintain your personal space in the well-used tunnel.\n\n<b>Dozens of obvious yet overlapping trip mines block the path north to the stairwell. You’ll have to find another way!</b>";
	rooms["WARGII R22"].planet = "PLANET: UVETO VII";
	rooms["WARGII R22"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R22"].moveMinutes = 2;
	rooms["WARGII R22"].northExit = "WARGII R20";
	rooms["WARGII R22"].eastExit = "WARGII T22";
	rooms["WARGII R22"].southExit = "";
	rooms["WARGII R22"].westExit = "";
	rooms["WARGII R22"].outExit = "";
	rooms["WARGII R22"].outText = "Down";
	rooms["WARGII R22"].inExit = "";
	rooms["WARGII R22"].inText = "Up";
	rooms["WARGII R22"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R22"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R22"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R22"].runOnEnter = wargiiR22Bonus;

	rooms["WARGII R20"] = new RoomClass(this);
	rooms["WARGII R20"].roomName = "B1 NORTHWEST\nSTAIRWELL";
	rooms["WARGII R20"].description = "Raw Savicite speckles the stairs and walls, bathing the entire area in a lovely green glow. Cum-stains are everywhere. The korgonne may be somewhat inoculated to Savicite’s arousing effects, but the milodan are not. Unconscious korgonne men and women alike doze in a cum-covered pile, discarded like used tissues. You’d best move on if you don’t want to be similarly affected. The stairs themselves are a little on the narrow side - perfect for small korgonne feet. You can climb up or back down to the hold’s ground floor.\n\nThe southern exit is blocked - not by rubble or a barricade but dozens of obvious trip-mines. You dare not disturb them and risk blowing this whole area to kingdom come.";
	rooms["WARGII R20"].planet = "PLANET: UVETO VII";
	rooms["WARGII R20"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R20"].moveMinutes = 2;
	rooms["WARGII R20"].northExit = "";
	rooms["WARGII R20"].eastExit = "";
	rooms["WARGII R20"].southExit = "WARGII R22";
	rooms["WARGII R20"].westExit = "";
	rooms["WARGII R20"].outExit = "WARGII R33";
	rooms["WARGII R20"].outText = "Down";
	rooms["WARGII R20"].inExit = "WARGII J6";
	rooms["WARGII R20"].inText = "Up";
	rooms["WARGII R20"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R20"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R20"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R20"].runOnEnter = wargiiR20Bonus;

	/*===============================================
	|   BASEMENT LEVEL 2 - B2 						|
	===============================================*/

	rooms["WARGII R43"] = new RoomClass(this);
	rooms["WARGII R43"].roomName = "B2 SOUTHWEST\nSTAIRWELL";
	rooms["WARGII R43"].description = "This deep into the hold, the stonework is a little rougher, a little less polished, yet still more refined than what you might encounter in your average terran park. It’s hotter here than higher up. Puddles of sweat dot the ground, probably left by hulking milodans unprepared for the heat. A rough-hewn tunnel lies north.";
	rooms["WARGII R43"].planet = "PLANET: UVETO VII";
	rooms["WARGII R43"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R43"].moveMinutes = 2;
	rooms["WARGII R43"].northExit = "WARGII R41";
	rooms["WARGII R43"].eastExit = "";
	rooms["WARGII R43"].southExit = "";
	rooms["WARGII R43"].westExit = "";
	rooms["WARGII R43"].outExit = "";
	rooms["WARGII R43"].outText = "Down";
	rooms["WARGII R43"].inExit = "WARGII R30";
	rooms["WARGII R43"].inText = "Up";
	rooms["WARGII R43"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R43"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R43"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R43"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R41"] = new RoomClass(this);
	rooms["WARGII R41"].roomName = "ROUGH-HEWN\nTUNNEL";
	rooms["WARGII R41"].description = "While this area is nicely widened out, the walls are textured with marks from chisels and picks. No effort has been made to clean up to the standards of the upper levels. A man-sized rent in the wall to the north glows with faint reddish light while the tunnel itself travels east.";
	rooms["WARGII R41"].planet = "PLANET: UVETO VII";
	rooms["WARGII R41"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R41"].moveMinutes = 2;
	rooms["WARGII R41"].northExit = "WARGII R39";
	rooms["WARGII R41"].eastExit = "WARGII T41";
	rooms["WARGII R41"].southExit = "WARGII R43";
	rooms["WARGII R41"].westExit = "";
	rooms["WARGII R41"].outExit = "";
	rooms["WARGII R41"].outText = "Down";
	rooms["WARGII R41"].inExit = "";
	rooms["WARGII R41"].inText = "Up";
	rooms["WARGII R41"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R41"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R41"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R41"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T41"] = new RoomClass(this);
	rooms["WARGII T41"].roomName = "ROUGH-HEWN\nTUNNEL";
	rooms["WARGII T41"].description = "The floor of this crudely hewn tunnel is perhaps the only area to receive attention from Korg’ii Hold’s builders; it’s flat and smooth, with nary a divot to stumble on. The walls aren’t so lucky, and if the surrounding minerals weren’t so strong, the lack of braces on the ceiling might worry you. You can follow the tunnel east and west from here.\n\nA huge door made of leather stretched over iron bars blocks the way north. The runes neatly scrawled onto its surface indicate the entrance to “Tamed Tamelings.”";
	rooms["WARGII T41"].planet = "PLANET: UVETO VII";
	rooms["WARGII T41"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T41"].moveMinutes = 2;
	rooms["WARGII T41"].northExit = "WARGII T39";
	rooms["WARGII T41"].eastExit = "WARGII V41";
	rooms["WARGII T41"].southExit = "";
	rooms["WARGII T41"].westExit = "WARGII R41";
	rooms["WARGII T41"].outExit = "";
	rooms["WARGII T41"].outText = "Down";
	rooms["WARGII T41"].inExit = "";
	rooms["WARGII T41"].inText = "Up";
	rooms["WARGII T41"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T41"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T41"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T41"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T39"] = new RoomClass(this);
	rooms["WARGII T39"].roomName = "TAMED\nTAMELINGS";
	rooms["WARGII T39"].description = "";
	rooms["WARGII T39"].planet = "PLANET: UVETO VII";
	rooms["WARGII T39"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T39"].moveMinutes = 2;
	rooms["WARGII T39"].northExit = "WARGII T37";
	rooms["WARGII T39"].eastExit = "WARGII V39";
	rooms["WARGII T39"].southExit = "WARGII T41";
	rooms["WARGII T39"].westExit = "";
	rooms["WARGII T39"].outExit = "";
	rooms["WARGII T39"].outText = "Down";
	rooms["WARGII T39"].inExit = "";
	rooms["WARGII T39"].inText = "Up";
	rooms["WARGII T39"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T39"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T39"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T39"].addFlag(GLOBAL.COMMERCE);
	rooms["WARGII T39"].runOnEnter = tamedTamelingsWarBonus;

	rooms["WARGII R39"] = new RoomClass(this);
	rooms["WARGII R39"].roomName = "GEOTHERMAL\nRENT";
	rooms["WARGII R39"].description = "Furnace-like heat blasts into you the moment you step into the room. Shielding your face, you observe that the chamber itself is naturally formed, not a product of korgonne tunneling. The more pressing concern is the bubbling pool of lava in the very center. A scan with your Codex reports the lava to be a mineral rich heat-vent from Uveto’s small but highly-active core, many miles below its liquid oceans.";
	rooms["WARGII R39"].planet = "PLANET: UVETO VII";
	rooms["WARGII R39"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R39"].moveMinutes = 2;
	rooms["WARGII R39"].northExit = "";
	rooms["WARGII R39"].eastExit = "";
	rooms["WARGII R39"].southExit = "WARGII R41";
	rooms["WARGII R39"].westExit = "";
	rooms["WARGII R39"].outExit = "";
	rooms["WARGII R39"].outText = "Down";
	rooms["WARGII R39"].inExit = "";
	rooms["WARGII R39"].inText = "Up";
	rooms["WARGII R39"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R39"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R39"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R39"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R39"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X43"] = new RoomClass(this);
	rooms["WARGII X43"].roomName = "B2 SOUTHEAST\nSTAIRWELL";
	rooms["WARGII X43"].description = "The bottom half of this staircase is a perfect example of rough tunneling, while the upper half is refined, decorated with artful inlays and inscriptions that depict the presence of many dwellings up above. The barrier between the two is obviously the result of simple pragmatism. In places where the korgonne spend most of their time, they’ve taken the time to create masterwork from their native stone. In less important locales, tunneling fast is more important. A rough-hewn tunnel leads away to the north.";
	rooms["WARGII X43"].planet = "PLANET: UVETO VII";
	rooms["WARGII X43"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X43"].moveMinutes = 2;
	rooms["WARGII X43"].northExit = "WARGII X41";
	rooms["WARGII X43"].eastExit = "";
	rooms["WARGII X43"].southExit = "";
	rooms["WARGII X43"].westExit = "";
	rooms["WARGII X43"].outExit = "";
	rooms["WARGII X43"].outText = "Down";
	rooms["WARGII X43"].inExit = "WARGII X30";
	rooms["WARGII X43"].inText = "Up";
	rooms["WARGII X43"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X43"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X43"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X43"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X41"] = new RoomClass(this);
	rooms["WARGII X41"].roomName = "ROUGH-HEWN\nTUNNEL";
	rooms["WARGII X41"].description = "A nearby geothermal vent has warmed the air on this level to near balmy levels. You can only imagine how a thick-furred korgonne would deal with the heat, naked or not. The rough-carved tunnel stretches away to the south or bends south to a stairwell. The passage’s floor is smooth and hazard free in both directions.";
	rooms["WARGII X41"].planet = "PLANET: UVETO VII";
	rooms["WARGII X41"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X41"].moveMinutes = 2;
	rooms["WARGII X41"].northExit = "";
	rooms["WARGII X41"].eastExit = "";
	rooms["WARGII X41"].southExit = "WARGII X43";
	rooms["WARGII X41"].westExit = "WARGII V41";
	rooms["WARGII X41"].outExit = "";
	rooms["WARGII X41"].outText = "Down";
	rooms["WARGII X41"].inExit = "";
	rooms["WARGII X41"].inText = "Up";
	rooms["WARGII X41"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X41"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X41"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X41"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V41"] = new RoomClass(this);
	rooms["WARGII V41"].roomName = "ROUGH-HEWN\nTUNNEL";
	rooms["WARGII V41"].description = "Bits of shiny but useless quartz sparkle in the walls and ceiling, left behind by miners intent on more valued prizes. The tunnel itself is carved straight along an east-west axis without much care for polish. They took the time to smooth the floor for comfort and safety but little else.";
	rooms["WARGII V41"].planet = "PLANET: UVETO VII";
	rooms["WARGII V41"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V41"].moveMinutes = 2;
	rooms["WARGII V41"].northExit = "";
	rooms["WARGII V41"].eastExit = "WARGII X41";
	rooms["WARGII V41"].southExit = "";
	rooms["WARGII V41"].westExit = "WARGII T41";
	rooms["WARGII V41"].outExit = "";
	rooms["WARGII V41"].outText = "Down";
	rooms["WARGII V41"].inExit = "";
	rooms["WARGII V41"].inText = "Up";
	rooms["WARGII V41"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V41"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V41"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V41"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V39"] = new RoomClass(this);
	rooms["WARGII V39"].roomName = "\nSTABLES";
	rooms["WARGII V39"].description = "This curved cavern is filled with fenced cages of all kinds. Pens for the korgonne’s animals are stocked with plenty of beasts, large and small. A few that seem to be nothing more than simple livestock, fuzzy things that shift around when you approach. A thin curving passage to the west leads back to the animal tamer’s place of business.";
	rooms["WARGII V39"].planet = "PLANET: UVETO VII";
	rooms["WARGII V39"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V39"].moveMinutes = 2;
	rooms["WARGII V39"].northExit = "WARGII V37";
	rooms["WARGII V39"].eastExit = "";
	rooms["WARGII V39"].southExit = "";
	rooms["WARGII V39"].westExit = "WARGII T39";
	rooms["WARGII V39"].outExit = "";
	rooms["WARGII V39"].outText = "Down";
	rooms["WARGII V39"].inExit = "";
	rooms["WARGII V39"].inText = "Up";
	rooms["WARGII V39"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V39"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V39"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V39"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V37"] = new RoomClass(this);
	rooms["WARGII V37"].roomName = "\nSTABLES";
	rooms["WARGII V37"].description = "";
	rooms["WARGII V37"].planet = "PLANET: UVETO VII";
	rooms["WARGII V37"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V37"].moveMinutes = 2;
	rooms["WARGII V37"].northExit = "";
	rooms["WARGII V37"].eastExit = "";
	rooms["WARGII V37"].southExit = "WARGII V39";
	rooms["WARGII V37"].westExit = "";
	rooms["WARGII V37"].outExit = "";
	rooms["WARGII V37"].outText = "Down";
	rooms["WARGII V37"].inExit = "";
	rooms["WARGII V37"].inText = "Up";
	rooms["WARGII V37"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V37"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V37"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V37"].runOnEnter = wargiiBeastCagesBonus;

	rooms["WARGII T37"] = new RoomClass(this);
	rooms["WARGII T37"].roomName = "REINFORCED\nTUNNEL";
	rooms["WARGII T37"].description = "Bolted-together metal bars brace this tunnel’s ceiling. You don’t see any particular reason why, but a Codex scan reveals the rock overhead to be comprised of a weaker mineral formulation. Evidently the keen-eyed dog-folk noticed something you didn’t - without the aid of a computer. A sturdy door, reinforced by gleaming titanium, offers entrance to the south. Carved runes suggest that it leads to “Tamed Tamelings.”";
	rooms["WARGII T37"].planet = "PLANET: UVETO VII";
	rooms["WARGII T37"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T37"].moveMinutes = 2;
	rooms["WARGII T37"].northExit = "WARGII T35";
	rooms["WARGII T37"].eastExit = "";
	rooms["WARGII T37"].southExit = "WARGII T39";
	rooms["WARGII T37"].westExit = "";
	rooms["WARGII T37"].outExit = "";
	rooms["WARGII T37"].outText = "Down";
	rooms["WARGII T37"].inExit = "";
	rooms["WARGII T37"].inText = "Up";
	rooms["WARGII T37"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T37"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T37"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T37"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII T35"] = new RoomClass(this);
	rooms["WARGII T35"].roomName = "GLASSY\nTUNNEL";
	rooms["WARGII T35"].description = "You can see your own reflection in the near-black volcanic glass that makes up the floor, walls, and much of the ceiling. It ripples and distorts with the imperfections in the tunnel’s surface as it makes its way to the east and west. Regular old rock frames a tunnel to the south, propped up by metal reinforcements.";
	rooms["WARGII T35"].planet = "PLANET: UVETO VII";
	rooms["WARGII T35"].system = "SYSTEM: SIRETTA";
	rooms["WARGII T35"].moveMinutes = 2;
	rooms["WARGII T35"].northExit = "";
	rooms["WARGII T35"].eastExit = "WARGII V35";
	rooms["WARGII T35"].southExit = "WARGII T37";
	rooms["WARGII T35"].westExit = "WARGII R35";
	rooms["WARGII T35"].outExit = "";
	rooms["WARGII T35"].outText = "Down";
	rooms["WARGII T35"].inExit = "";
	rooms["WARGII T35"].inText = "Up";
	rooms["WARGII T35"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII T35"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII T35"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII T35"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R35"] = new RoomClass(this);
	rooms["WARGII R35"].roomName = "GLASSY\nTUNNEL";
	rooms["WARGII R35"].description = "Solid rock gives way to a near-transparent volcanic glass this deep into the hold. Striations of mineral impurities lay down stripes and blotches, preventing it from being having a perfect mirror sheen. A staircase climbs up and away to the north, while the tunnel itself burrows eastward into the hold.";
	rooms["WARGII R35"].planet = "PLANET: UVETO VII";
	rooms["WARGII R35"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R35"].moveMinutes = 2;
	rooms["WARGII R35"].northExit = "WARGII R33";
	rooms["WARGII R35"].eastExit = "WARGII T35";
	rooms["WARGII R35"].southExit = "";
	rooms["WARGII R35"].westExit = "";
	rooms["WARGII R35"].outExit = "";
	rooms["WARGII R35"].outText = "Down";
	rooms["WARGII R35"].inExit = "";
	rooms["WARGII R35"].inText = "Up";
	rooms["WARGII R35"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R35"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R35"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R35"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII R33"] = new RoomClass(this);
	rooms["WARGII R33"].roomName = "B2 NORTHWEST\nSTAIRWELL";
	rooms["WARGII R33"].description = "You stand at the landing for a narrow staircase. Speckled Savicite in the walls provides dim but eerie green light to guide travelers on their way. Apparently the korgonne would rather admire its beauty than dig it out of the walls for its numerous industrial uses. Going any further down seems pointless, but if you’d like to climb higher into the hold, this is the place. A cramped doorway on the south wall offers access to a glassy passageway.";
	rooms["WARGII R33"].planet = "PLANET: UVETO VII";
	rooms["WARGII R33"].system = "SYSTEM: SIRETTA";
	rooms["WARGII R33"].moveMinutes = 2;
	rooms["WARGII R33"].northExit = "";
	rooms["WARGII R33"].eastExit = "";
	rooms["WARGII R33"].southExit = "WARGII R35";
	rooms["WARGII R33"].westExit = "";
	rooms["WARGII R33"].outExit = "";
	rooms["WARGII R33"].outText = "Down";
	rooms["WARGII R33"].inExit = "WARGII R20";
	rooms["WARGII R33"].inText = "Up";
	rooms["WARGII R33"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII R33"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII R33"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII R33"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X35"] = new RoomClass(this);
	rooms["WARGII X35"].roomName = "GLASSY\nTUNNEL";
	rooms["WARGII X35"].description = "The inky, volcanic stone floor was polished to a near mirror finish before the battle spread to this part of the hold. Now it is scratched by blades and claws, then scuffed by spiked boots. You can duck into a stairwell’s landing through an opening on the north or follow this reflective passage to its conclusion, westward."
	rooms["WARGII X35"].planet = "PLANET: UVETO VII";
	rooms["WARGII X35"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X35"].moveMinutes = 2;
	rooms["WARGII X35"].northExit = "WARGII X33";
	rooms["WARGII X35"].eastExit = "";
	rooms["WARGII X35"].southExit = "";
	rooms["WARGII X35"].westExit = "WARGII V35";
	rooms["WARGII X35"].outExit = "";
	rooms["WARGII X35"].outText = "Down";
	rooms["WARGII X35"].inExit = "";
	rooms["WARGII X35"].inText = "Up";
	rooms["WARGII X35"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X35"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X35"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X35"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII V35"] = new RoomClass(this);
	rooms["WARGII V35"].roomName = "GLASSY\nTUNNEL";
	rooms["WARGII V35"].description = "You’re surprised that you haven’t stumbled upon a milodan with a broken leg yet. This floor is treacherously slick, though the korgonne seem to have no problems navigating it. For a half-second, you consider skating around in socks.";
	rooms["WARGII V35"].planet = "PLANET: UVETO VII";
	rooms["WARGII V35"].system = "SYSTEM: SIRETTA";
	rooms["WARGII V35"].moveMinutes = 2;
	rooms["WARGII V35"].northExit = "";
	rooms["WARGII V35"].eastExit = "WARGII X35";
	rooms["WARGII V35"].southExit = "";
	rooms["WARGII V35"].westExit = "WARGII T35";
	rooms["WARGII V35"].outExit = "";
	rooms["WARGII V35"].outText = "Down";
	rooms["WARGII V35"].inExit = "";
	rooms["WARGII V35"].inText = "Up";
	rooms["WARGII V35"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII V35"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII V35"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII V35"].runOnEnter = wargiiEncounterStuff;

	rooms["WARGII X33"] = new RoomClass(this);
	rooms["WARGII X33"].roomName = "B2 NORTHEAST\nSTAIRWELL";
	rooms["WARGII X33"].description = "Marbled purple veins run through the underlying stone of this hand-carved staircase. This low into the hold, foot traffic is at a minimum, though hints of battle are everywhere. Sweat, blood, and cum all make appearances on the floor. You can climb back up or travel south onto a glassy corridor.";
	rooms["WARGII X33"].planet = "PLANET: UVETO VII";
	rooms["WARGII X33"].system = "SYSTEM: SIRETTA";
	rooms["WARGII X33"].moveMinutes = 2;
	rooms["WARGII X33"].northExit = "";
	rooms["WARGII X33"].eastExit = "";
	rooms["WARGII X33"].southExit = "WARGII X35";
	rooms["WARGII X33"].westExit = "";
	rooms["WARGII X33"].outExit = "";
	rooms["WARGII X33"].outText = "Down";
	rooms["WARGII X33"].inExit = "WARGII X20";
	rooms["WARGII X33"].inText = "Up";
	rooms["WARGII X33"].addFlag(GLOBAL.INDOOR);
	//rooms["WARGII X33"].addFlag(GLOBAL.PUBLIC);
	rooms["WARGII X33"].addFlag(GLOBAL.HAZARD);
	rooms["WARGII X33"].runOnEnter = wargiiEncounterStuff;
}