public function zilNightScienceBiPlay():void
{
	clearMenu();
	clearOutput();
	processTime(23);
	author("Gardeford");

	output("You give the crudely titled video-chip a last look before inserting it into your room's video display. Almost immediately a brightly colored 3D title appears, followed quickly by an interactive message from the film company.");
	output("\n\n<i>\"Girderbeam technologies Ltd. brings you the latest in gate world adult filmography! Thanks to one of our close collaborators, Doctor Julius Haswill, we have a new star in the form of Zil Nigh! Mr. Nigh will be replacing Garnoth Sahnsmith (sorry if this is the first you hear of this Garnoth, after that Throbb mishap we can't really afford to ship you from location to location.) In this, his debut film, our new movie star plays a dashing doctor with a beautiful, busty nurse. What fun will he get up to when his most recent experiment goes horribly wrong? Also buy our other new films: Nightmares are Sexy Too, Zil Nigh: Private Eye, and Fuckwatch.\"</i>");
	output("\n\nYou give the computer the command to skip straight to the video. A company logo flashes: a large girder beam with a pair of wrecking balls chained to one end, before the video abruptly starts. ");
	output("\n\nA male zil stands in a rather dingy looking lab room. He wears nothing but a white labcoat, his lengthy prick and melon-sized balls remaining completely exposed. He holds a movie script, looking rather confused. Beside him stands an incredibly busty human woman you recognize as Becky Bigevajj, an actress known for taking large insertions. She's in a similar state of dress, wearing only a labcoat, bra, thong, and a pair of nerdy glasses that look entirely out of place.");
	output("\n\n<i>\"Doctor! I accidentally dropped the vial of extremely volatile lust drug and it broke on the ground! What are we going to do!?\"</i> she shouts, putting an arm over her forehead dramatically and thrusting her chest out. The zil looks hastily at the script, narrowing his eyes and gulping. ");
	output("\n\n<i>\"I, ah, ahem. W-we only have mere minutes until we're reduced to fucking like amin- animals! We have to administer the antidote!\"</i> he squeaks, his eyes widening after he seems to comprehend what he is reading. His glossy zil-cock stirs with arousal. Becky takes note, sauntering closer to the hapless looking bug-boy. ");
	output("\n\n<i>\"Oh doctor. I can already feel it inside me. It might be... too late,\"</i> she gives a look of mock concern as she unhooks and pulls away her bra. The alien doctor's eyes go even wider, his dick rising the rest of the way as he ogles his fellow actress's impossibly perky F-cups. She kneels down, planting a kiss on his foreskin-sheathed head. The voluptuous woman grins when a shiver runs through his spine, complete with a flutter of movement from his tiny wings. He seems to come to a sudden realization through his shudders, pulling the script up in a shaky grip.");
	output("\n\n<i>\"I- oohhh. You're right. M-my base instincts are coming through. I have to fuck!\"</i> You're no longer sure how much of this is script and how much is real. He runs his chitonous fingers through her hair as she lathers his dick with an even shinier coating of saliva. The platinum blonde <i>\"scientist\"</i> takes his full length, not struggling for a second as each inch of shiny schlong glides into her throat. ");
	output("\n\nA shaky camera transition takes you behind the action, seeing the Zil actor's tight butt clenching as his oversized balls bounce against the larger woman's breasts. As the shot pans around, you can see him bucking his hips into her mouth. Saliva and precum dribble down her chin and onto her tits, coating them in a similar sheen to the cock she fellates.");
	output("\n\n<i>\"I'm gonna cum! S-sorry miss,\"</i> he blurts suddenly. Becky's eyes widen as the zil grasps both sides of her head, thrusting wildly before hilting himself against her plush lips. The base of his glossy member pulses a few times before her eyes roll back, honey spurting out of her nose and mouth in globs. He pulls slowly back, barely managing to resist the bowing of his legs that accompanies every throb of his orgasming honeystick. ");
	output("\n\nHe isn't finished cumming by the time he tugs free of her lips, still connected by strands of sweetened semen. Thick ropes of honey spew from his tip, plastering her chest with golden lust. The actress struggles to get her bearings, absentmindedly pinching a sugar coated nipple as her eyes dilate and cross.");
	output("\n\n<i>\"What'd you do? Smell so good, so hot,\"</i> she murmurs, turning around and Hiking the pearly labcoat up over her back. Her efforts reveal a pair of thin dark panties that do nothing to contain her quivering alabaster ass. She tries in vain to tug the soaked undergarments down, moaning in distress as the waistband fails to crest her bountiful bottom. Finally, she resorts to pulling them aside to reveal her twitching cunt. ");
	output("\n\n<i>\"Please. Want more,\"</i> she begs incoherently, tightening her grip on her underwear. The petite zil all but jumps onto her, his spit-polished cock pushing nearly to the hilt in a single thrust. The pheromone-flushed actress abandons her hold, transitioning it to a nearby chair in an attempt to stay on her knees as her body is rocked by orgasm. ");
	output("\n\nDeep, guttural moans are cut short as the Zil's thighs slap thunderously against her own. Honey slicked hands lose traction on the tile floor, sending her prone against the ground. With each thrust her F-cup breasts press into the floor, jiggling in time with the pounding. Her drenched thighs try their best to clench together, but they only provide a bigger buffer for his hips to slap against.");
	output("\n\n<i>\"N-no protection. Gonna get p-pregnant,\"</i> she slurs, a half delirious grin painting her features. The madly thrusting bug-boy hugs tightly to her back, kissing her neck as he buries himself inside her. You see her hips buck up, carrying him along for the ride as she cums. At first all you see is him giving a couple weak thrusts, but then a splurt of honey gushes out of her sex engorged cunt, leveling off into a thin waterfall that floods down to the floor. ");
	output("\n\nWhat remains of the script lies in tatters in a puddle of thick honey, with the actors reduced to an atavistic display of impregnation. The raw need in their shared moans is intoxicating. You can even hear the ragged breathing of the cameraman as he gets closer to the action. The zil boy is still cumming when the camera zooms in on their connected sexes, and you can see the base of his cock surge with a fresh load through the hazy amber flood that oozes down the overfucked pornstar's legs. You can almost smell the sweet slurry through the screen.");
	output("\n\nThe camera pans to their faces, but neither seem to notice. The zil is too short to reach her for a kiss, and settles for lying against her back and squeezing her enormous tits. His eyes fade in and out of focus as his seemingly endless orgasm continues. Becky shares in his vapid relaxation. Her fists clench occasionally, but she's all but given up on fighting the deluge of seed filling her womb. Gooey nectar from the first round still coats her face, smeared on the polished lab floor by the earlier friction.");
	output("\n\nAfter another solid minute of cumming, the leading lady's belly is swollen with candied filling. She looks almost pregnant. The frenzied zil finally slips free, his foreskinned cock softening to a slightly more reasonable size. His chest heaves, and he seems to slowly come back to his senses. He looks around, gasping when he seems to realize what's happened.");
	output("\n\n<i>\"Oh! Oh g-gosh. Sorry miss, but I'm not too good at controlling my urges since this whole science thing. I think you off-worlders do this after?\"</i> he explains, leaning down and pulling her into a long kiss. She kisses him back automatically, still most definitely <i>not</i> recovered from the ordeal. Honey oozes in viscous globs from her cunt as the movement forces some of it out of her womb.");
	output("\n\n<i>\"W-well. Is that the end of the show? The s-script is gone so I don't really know what to do now.\"</i> He pats his thighs, looking at the camera with an embarrassed smile. Suddenly, there is a loud knocking on the lab room door.");
	output("\n\n<i>\"Hey! What are you doing in there! You aren't allowed in this lab room. If you don't unlock this door, I will call the police!\"</i> A nasaly voice shouts from just outside. The zil star looks confused, still grinning as the cameraman seems to scramble for something off screen. A sudden burst of bright green light streaks across the screen, taking half the far wall with it when it dims down. Exposed wall and circuitry frames a five meter thick hole in the wall, revealing the open bay doors of a rattling passenger cruiser. A number of crew members dash on, some carrying equipment and others carrying the cast members. The footage abruptly cuts to black mid exit, leaving you staring at the black screen in bewilderment.");
	output("\n\nYour video display ejects the chip, and you shake your head. Whatever this film company is doing, you can't imagine they'll be doing it long.");

    pc.lust(30+pc.libido()/4);
	addButton(0,"Next",mainGameMenu);
}