
function hangarBonus():Boolean 
{
	trace("this", this);
	// trace("this.titsClassPtr.move,", this.titsClassPtr.move);
	// trace("this.titsClassPtr.userInterface", this.titsClassPtr.userInterface);
	if(currentLocation == "LIFT: MERCHANT DECK") {
		userInterface.addButton(5,"ToHangar",liftMove, "TAVROS LIFT");
	}
	else if(currentLocation == "TAVROS LIFT") {
		userInterface.addButton(5,"ToMerchant",liftMove, "LIFT: MERCHANT DECK");
	}
	return false;
}
function liftMove(destination:String):void {
	move(destination,false);
	clearOutput();
	output("Your stomach drops as the lift kicks into gear. The gentle, steady thrum of powerful machinery fills the metallic tube as you are brought to your destination, slowly decelerating when you arrive.");
	userInterface.clearMenu();
	userInterface.addButton(0,"Next",mainGameMenu);
}


function debugMenus():void
{
	userInterface.clearMenu();
	output("The room of debug. Where am I? How did I get here? What do you want?!");
	userInterface.addButton(0, "Hit self", function():void { 
		chars["PC"].HP(-1); 
		chars["PC"].shieldsRaw -= 1; 
	} );
	userInterface.addButton(5, "Unhit self", function():void {
		chars["PC"].HP(5);
		chars["PC"].shieldsRaw += 5;
	} );
	
	userInterface.addButton(2, "SPACEPRONS", function():void {
		chars["PC"].lust(5);
	} );
	userInterface.addButton(7, "Fapfapfap", function():void {
		chars["PC"].lust(0, true);
	} );
	
	userInterface.addButton(3, "Sleepy", function():void {
		chars["PC"].energy( -5);
	} );
	userInterface.addButton(8, "POWER UP", function():void {
		chars["PC"].energy(5);
	} );
	
	userInterface.addButton(1, "Sam Ipsun", function():void {
		(chars["PC"] as PlayerCharacter).createStatusEffect("Zil Sting",4,0,0,0,false,"Poison","Zil Toxin: Reduces speed and increases libido.",false,55+rand(10));
	} );
	userInterface.addButton(4, "Effecty", function():void {
		(chars["PC"] as PlayerCharacter).createStatusEffect("Test Effect", 0, 0, 0, 0, false, "Icon_Test", "This is a test effect generated by a debug menu. It does precisely fuck all apart from exist to test the status effect display system.\n - FNN\n\n<b>Would you like to know more?</b>\n<b><font color='#0CD71C'>[Yes]</font><font color='#FF0000'>[No]</font></b>", false, 60);
	} );
	userInterface.addButton(9, "R.Effect", function():void {
		(chars["PC"] as PlayerCharacter).createStatusEffect("Effect" + String(rand(100)), 0, 0, 0, 0, false, "Icon_DoesNotExist", "This is a test effect generated by a debug menu. It is randomly named to further assist in the debugging of things that are complicated. It does precisely fuck all apart from exist to test the status effect display system.\n - FNN\n\n<b>Would you like to know more?</b>\n<b><font color='#0CD71C'>[Yes]</font><font color='#FF0000'>[No]</font></b>", false, 60);
	} );
	userInterface.addButton(13, "S.Dick", function():void {
		(chars["PC"] as PlayerCharacter).createStatusEffect("SmartDick v1.4", 0, 0, 0, 0, false, "Icon_RadioSignal", "Thanks to the wonderful Dr. REDACTED, your package is now laced with nanites, granting it basic sentience and the ability to move independently. Due to your modest size at the time of \"installation,\" your penis is only capable of acting on basic commands, such as vibration or alerting you to unusual activity, and is not self-aware.\n\nYour augmented tool is capable of <b><font color='#0CD71C'>slight lust prevention</font></b> in battle. This feature can be disabled upon request. The interconnected nature of your dick also makes it more susceptible to <b><font color='#FF0000'>computer viruses</font></b> and various other technological attacks, so it is recommended to take caution around more tech-savy adversaries.\n\nMore benefits (or drawbacks) may be available in future \"firmware updates.\"", false, 120);
	} );
}


/*
Fern, Lichens, and Ironwoods:
Man/FemZil, Cuntsnake

Dense Orange, Dark, Narrow Path
Naleen, Cuntsnake, Venus Pitchers

Deep Jungle Biome:
Naleen, Venus Pitchers, Elder Venus Pitchers, Zil
*/
function jungleEncounterChances():Boolean {
	if(flags["JUNGLE_STEP"] == undefined) flags["JUNGLE_STEP"] = 1;
	else flags["JUNGLE_STEP"]++;
	
	var choices:Array = new Array();
	//If walked far enough w/o an encounter
	if(flags["JUNGLE_STEP"] >= 6 && rand(4) == 0) {
		//Reset step counter
		flags["JUNGLE_STEP"] = 0;
		
		if(debug) {
			maleZilEncounter();
			return true;
		}
		
		//Build possible encounters
		choices[choices.length] = femzilEncounter;
		choices[choices.length] = maleZilEncounter;
		choices[choices.length] = encounterCuntSnakeOnJungleLand;
		
		//Run the event
		choices[rand(choices.length)]();
		return true;
	}
	return false;
}

function jungleMiddleEncounters():Boolean {
	if(flags["JUNGLE_STEP"] == undefined) flags["JUNGLE_STEP"] = 1;
	else flags["JUNGLE_STEP"]++;
	
	var choices:Array = new Array();
	//If walked far enough w/o an encounter
	if(flags["JUNGLE_STEP"] >= 5 && rand(3) == 0) {
		//Reset step counter
		flags["JUNGLE_STEP"] = 0;
		
		//Build possible encounters
		if((userInterface.hours < 3 || userInterface.hours > 20) && totalNaleenSexCount() >= 5)
			choices[choices.length] = naleenNightCuddles;
		else choices[choices.length] = encounterNaleen;
		choices[choices.length] = encounterCuntSnakeOnJungleLand;
		choices[choices.length] = encounterRegularTentaclePitcherYouGay;
		
		//Run the event
		choices[rand(choices.length)]();
		return true;
	}
	return false;
}
function findOxoniumOnMhenga():Boolean {
	if(flags["TAGGED_MHENGA_OXONIUM_DEPOSIT"] == undefined) {
		output("\n\nThere is a vertical striation running up through the rock wall of a different mineral, something pitch black that seems to draw in the light. You could probably scan it with your codex and radio it in to your Dad's company for a quick prospector's fee.");
	}
	else {
		output("\n\nThere's a deposit of Oxonium here, but you've already called in the claim to your Dad's company. They'll probably be out to mine it once the frontier settles down a little bit.");
	}
	//Overridden by Jungle deep encounters
	if(jungleDeepEncounters()) return true;
	//Option to loot it!
	else if(flags["TAGGED_MHENGA_OXONIUM_DEPOSIT"] == undefined) {
		userInterface.addButton(0,"Scan Rock",claimMhengaOxonium);
	}
	return false;
}
function claimMhengaOxonium():void {
	clearOutput();
	output("Utilizing your codex's sensors, you identify the material as Oxonium, a rare mineral used in holographic displays. There amount here is decent, easily worth at least 3,000 credits. You record your location and compose a short message, sending it off a few minutes later. Before you've had a chance to do anything else, the codex beeps.\n\n<b>Your bank account just got a 5,000 credit deposit.</b> Either you're not a great geologist, or Dad's company has orders to give you top dollar. Regardless, the profit is yours.");
	
	flags["TAGGED_MHENGA_OXONIUM_DEPOSIT"] = 1;
	if(flags["OXONIUM_FOUND"] == undefined) flags["OXONIUM_FOUND"] = 0;
	flags["OXONIUM_FOUND"]++;
	pc.credits += 5000;
	processTime(6);
	userInterface.clearMenu();
	userInterface.addButton(0,"Next",mainGameMenu);
}

function jungleDeepEncounters():Boolean {
	if(flags["JUNGLE_STEP"] == undefined) flags["JUNGLE_STEP"] = 1;
	else flags["JUNGLE_STEP"]++;
	
	var choices:Array = new Array();
	//If walked far enough w/o an encounter
	if(flags["JUNGLE_STEP"] >= 5 && rand(2) == 0) {
		//Reset step counter
		flags["JUNGLE_STEP"] = 0;
		
		//Build possible encounters
		if((userInterface.hours < 3 || userInterface.hours > 20) && totalNaleenSexCount() >= 5)
			choices[choices.length] = naleenNightCuddles;
		else choices[choices.length] = encounterNaleen;
		choices[choices.length] = femzilEncounter;
		choices[choices.length] = maleZilEncounter;
		choices[choices.length] = encounterRegularTentaclePitcherYouGay;
		choices[choices.length] = elderVenusPitcherEncounter;
		
		//Run the event
		choices[rand(choices.length)]();
		return true;
	}
	return false;
}